import mongoose, { Document, Schema } from 'mongoose';

export interface IInterviewQuestion extends Document {
    sessionId: mongoose.Types.ObjectId; // Link to the parent session
    moduleId: string; // Link to module ID in InterviewSession.modules

    // The content generated by AI
    content: {
        question: string;
        whyAsked?: string; // AI explanation of why this question matters
        difficulty: 'easy' | 'medium' | 'hard';
        tags: string[];
    };

    // "Your Edge" - Personalized tips based on user's CV
    edgeTip?: {
        content: string;
        sourceCVId?: mongoose.Types.ObjectId; // Which CV was used to generate this tip
        relevantExperience?: string; // Specific experience cited (e.g. "Your time at Google")
    };

    // User's interaction
    userAnswer?: {
        text: string;
        audioUrl?: string; // Future proofing
        draftLastSavedAt?: Date;
        submittedAt?: Date;
        status: 'draft' | 'analyzed' | 'skipped';
    };

    // AI Analysis of the answer
    aiFeedback?: {
        score: number; // 0-100
        strengths: string[];
        improvements: string[];
        improvedScript?: string; // AI rewritten version
        sentiment?: 'positive' | 'neutral' | 'negative' | 'uncertain';
        analyzedAt: Date;
    };

    displayOrder: number;
    isHighRelevance: boolean; // Flag for questions that directly match JD keywords

    createdAt: Date;
    updatedAt: Date;
}

const interviewQuestionSchema = new Schema<IInterviewQuestion>({
    sessionId: {
        type: Schema.Types.ObjectId,
        ref: 'InterviewSession',
        required: true
    },
    moduleId: {
        type: String,
        required: true
    },
    content: {
        question: { type: String, required: true },
        whyAsked: { type: String },
        difficulty: {
            type: String,
            enum: ['easy', 'medium', 'hard'],
            default: 'medium'
        },
        tags: [{ type: String }]
    },
    edgeTip: {
        content: { type: String },
        sourceCVId: { type: Schema.Types.ObjectId, ref: 'CV' },
        relevantExperience: { type: String }
    },
    userAnswer: {
        text: { type: String },
        audioUrl: { type: String },
        draftLastSavedAt: { type: Date },
        submittedAt: { type: Date },
        status: {
            type: String,
            enum: ['draft', 'analyzed', 'skipped'],
            default: 'draft'
        }
    },
    aiFeedback: {
        score: { type: Number },
        strengths: [{ type: String }],
        improvements: [{ type: String }],
        improvedScript: { type: String },
        sentiment: { type: String },
        analyzedAt: { type: Date }
    },
    displayOrder: {
        type: Number,
        default: 0
    },
    isHighRelevance: {
        type: Boolean,
        default: false
    }
}, {
    timestamps: true,
    toJSON: {
        transform: function (doc, ret: any) {
            ret.id = ret._id;
            delete ret._id;
            delete ret.__v;
            return ret;
        }
    }
});

// Indexes
interviewQuestionSchema.index({ sessionId: 1, moduleId: 1 }); // Fetch questions for a session module
interviewQuestionSchema.index({ sessionId: 1, 'userAnswer.status': 1 }); // Track progress (e.g. how many analyzed)

export default mongoose.models.InterviewQuestion || mongoose.model<IInterviewQuestion>('InterviewQuestion', interviewQuestionSchema);
