'use client';

import React, { createContext, useContext, useReducer, ReactNode } from 'react';
import { UnifiedCVDataStructure, DEFAULT_UNIFIED_CV_DATA } from '@/types/unified-cv-schema';
import { ITemplate } from '@/types/template';
import type { FixAnnotation } from '@/components/resume-enhancer/annotations/fix-annotation';
import { CVSurgeonService, type SurgicalFix } from '@/lib/services/cv-surgeon-service';
import type { KeywordGap, KeywordGapAnalysisResult } from '@/types/keyword-gap';
import { getAnalysisMode, getAnalysisModeWithValidation, hasAnalysisContextChanged, type AnalysisMode, type AnalysisModeResult, type AnalysisModeInfo } from '@/lib/utils/analysis-mode';
import { type DateFormatStyle } from '@/lib/utils/textFormatting';
import { type PaperSize } from '@/lib/services/paperSizeService';

// State Interface
export interface ResumeEnhancerState {
  // Mode and navigation
  mode: 'create' | 'edit';
  currentStep: 1 | 2 | 3 | 4 | 5;

  // CV identification
  cvId?: string;
  cvType: 'master' | 'journey' | 'standalone';
  cvTitle: string;

  // CV data
  cvData: UnifiedCVDataStructure;

  // Template
  selectedTemplate: ITemplate | null;

  // Role context
  targetRole: string;
  seniorityLevel: string;

  // Job/Journey context
  jobData?: any;
  journeyId?: string;

  // AI Analysis
  surgeonAnalysis: { score: number; fixes: SurgicalFix[] } | null;
  isAnalyzing: boolean;

  // Legacy/overlay state (used by ResumeEnhancerClient + overlays)
  showProfilerModal: boolean;
  showSurgeonOverlay: boolean;
  showPreviewOverlay: boolean;
  cvScore: number;
  surgicalFixes: SurgicalFix[];

  // Report / Review & Fix mode (Step 3)
  fixAnnotations: FixAnnotation[];
  reportOpen: boolean;
  reviewMode: boolean;
  activeFixId?: string;

  // Save state
  isSaving: boolean;
  saveError: string | null;

  // Session tracking
  sessionStartTime: number;
  stepStartTimes: Record<number, number>;

  // Loop breaker state
  currentCVHash?: string; // Hash of current CV to detect fundamental changes
  suppressedFixHashes: string[]; // List of suppressed fix signature hashes

  // Career Ecosystem: Master CV & Fresher Mode
  isUserMaster: boolean; // Is this THE user's single Master CV
  fresherMode: boolean; // Education/Projects first layout (no work experience)
  hasMasterCV: boolean; // Does user already have a Master CV
  isFirstCVCreation: boolean; // Is this the first CV the user is creating (0 CVs exist)
  enforceMasterCVMode: boolean; // Lock UI to Master CV mode when creating first CV

  // Career Ecosystem: ATS Score & Template Cap
  atsScoreCap: number; // Template-based cap (default 100, creative = 70)
  atsScore: number; // ATS match score for Journey CVs (0-100)

  // Career Ecosystem: Keyword Gap Analysis (Journey mode)
  keywordGaps: KeywordGap[]; // Missing JD keywords
  keywordGapAnalysis: KeywordGapAnalysisResult | null; // Full analysis result
  isAnalyzingKeywords: boolean; // Loading state for keyword analysis

  // Career Ecosystem: Auto-generated Cover Letter
  autoGeneratedCoverLetter?: string; // Draft cover letter body
  coverLetterId?: string; // ID of created cover letter

  // Career Ecosystem: JD Input (for Step 1 Journey flow)
  jdText: string; // Raw JD text pasted by user
  jdWordCount: number; // Word count for validation

  // Analysis Mode (computed from cvType, role, and JD)
  analysisMode: AnalysisMode;

  // Enhanced Analysis Mode with Validation (NEW)
  analysisModeInfo: AnalysisModeInfo | null;
  lastAnalysisContext: {
    mode: AnalysisMode;
    roleHash: string;
    jdHash: string;
  } | null;
  modeTransitionWarnings: string[];
  modeTransitionData: { fromMode: AnalysisMode; toMode: AnalysisMode; transitionType: string } | null;

  // Score multipliers and breakdowns (for enhance.md formulas)
  cvScoreMultiplier: number;           // V factor (0.2 or 1.0)
  cvScoreBreakdown: Record<string, number> | null; // C, I, Q, F, R
  cvPenaltyReasons: string[];          // Reasons for score penalty
  atsScoreMultiplier: number;          // P factor (0.1 or 1.0)
  atsScoreBreakdown: Record<string, number> | null; // K, F, S, R, C
  atsScoreContext: 'jd-specific' | 'industry-general';

  // Simulated CV toggle and strategic fix data
  showSimulatedCV: boolean;
  strategicFixAvailable: boolean;
  strategicFixData: any | null;        // CV data with strategic projects
  authenticOptData: any | null;        // Authentic optimization data
  annotationLog: { path: string; action: string; reason: string }[];
  nextSteps: string[];

  // Document Formatting Preferences
  dateFormat: DateFormatStyle;  // User-selected date format for CV
  paperSize: PaperSize;         // Detected or user-selected paper size

  // Centralized View State (Phase 3)
  isJobSidebarOpen: boolean;
  isTemplateOverlayOpen: boolean;

  // Mori Chat Mode
  moriChatMode: boolean;
}

// Action Types
type ResumeEnhancerAction =
  | { type: 'SET_MODE'; payload: 'create' | 'edit' }
  | { type: 'SET_STEP'; payload: 1 | 2 | 3 | 4 | 5 }
  // Back-compat aliases used by older ResumeEnhancerClient implementation
  | { type: 'SET_CURRENT_STEP'; payload: 1 | 2 | 3 | 4 | 5 }
  | { type: 'SET_CV_ID'; payload: string }
  | { type: 'SET_CV_TYPE'; payload: 'master' | 'journey' | 'standalone' }
  | { type: 'SET_CV_TITLE'; payload: string }
  | { type: 'UPDATE_CV_DATA'; payload: Partial<UnifiedCVDataStructure> }
  | { type: 'SET_CV_DATA'; payload: UnifiedCVDataStructure }
  | { type: 'SET_TEMPLATE'; payload: ITemplate | null }
  | { type: 'SET_SELECTED_TEMPLATE'; payload: ITemplate | null }
  | { type: 'SET_ROLE_CONTEXT'; payload: { targetRole: string; seniorityLevel: string } }
  | { type: 'SET_TARGET_ROLE'; payload: string }
  | { type: 'SET_SENIORITY_LEVEL'; payload: string }
  | { type: 'SET_JOB_DATA'; payload: any }
  | { type: 'SET_JOURNEY_ID'; payload: string }
  | { type: 'CONVERT_TO_JOURNEY'; payload: { journeyId: string; jobData: any; coverLetterId?: string; coverLetterDraft?: string } }
  | { type: 'SET_SURGEON_ANALYSIS'; payload: { score: number; fixes: SurgicalFix[] } }
  | { type: 'SET_FIX_ANNOTATIONS'; payload: FixAnnotation[] }
  | { type: 'SET_REPORT_OPEN'; payload: boolean }
  | { type: 'SET_REVIEW_MODE'; payload: boolean }
  | { type: 'SET_ACTIVE_FIX'; payload: string | undefined }
  | { type: 'MARK_FIX_APPLIED'; payload: string }
  | { type: 'MARK_FIX_DISMISSED'; payload: string }
  | { type: 'MARK_FIX_SUPPRESSED'; payload: { fixId: string; reason: 'manual_override' | 'semantic_detected' | 'conflict_resolution'; fixSignatureHash?: string } }
  | { type: 'MARK_FIX_SEMANTIC_MATCH'; payload: { fixId: string; foundTerm: string; confidence: number } }
  | { type: 'SET_ANALYZING'; payload: boolean }
  | { type: 'SET_SHOW_PROFILER_MODAL'; payload: boolean }
  | { type: 'SET_SHOW_SURGEON_OVERLAY'; payload: boolean }
  | { type: 'SET_SHOW_PREVIEW_OVERLAY'; payload: boolean }
  | { type: 'APPLY_SURGICAL_FIX'; payload: string }
  | { type: 'UPDATE_SURGICAL_FIX_STATUS'; payload: { id: string; status: 'pending' | 'accepted' | 'rejected' } }
  | { type: 'SET_SAVING'; payload: boolean }
  | { type: 'SET_SAVE_ERROR'; payload: string | null }
  | { type: 'RESET_STATE' }
  | { type: 'LOAD_CV'; payload: { cvId: string; cvType: 'master' | 'journey' | 'standalone'; cvTitle: string; cvData: UnifiedCVDataStructure; template?: ITemplate; journeyId?: string; jobData?: any; coverLetterId?: string } }
  // Career Ecosystem Actions
  | { type: 'SET_IS_USER_MASTER'; payload: boolean }
  | { type: 'SET_FRESHER_MODE'; payload: boolean }
  | { type: 'SET_HAS_MASTER_CV'; payload: boolean }
  | { type: 'SET_IS_FIRST_CV_CREATION'; payload: boolean }
  | { type: 'SET_ENFORCE_MASTER_CV_MODE'; payload: boolean }
  | { type: 'SET_ATS_SCORE_CAP'; payload: number }
  | { type: 'SET_ATS_SCORE'; payload: number }
  | { type: 'SET_KEYWORD_GAPS'; payload: KeywordGap[] }
  | { type: 'SET_KEYWORD_GAP_ANALYSIS'; payload: KeywordGapAnalysisResult | null }
  | { type: 'SET_ANALYZING_KEYWORDS'; payload: boolean }
  | { type: 'UPDATE_KEYWORD_GAP'; payload: { keyword: string; updates: Partial<KeywordGap> } }
  | { type: 'SET_AUTO_COVER_LETTER'; payload: { draft: string; coverLetterId?: string } }
  | { type: 'SET_JD_TEXT'; payload: string }
  | { type: 'CLEAR_JD_TEXT' }
  // Validation Actions (NEW)
  | { type: 'SET_ANALYSIS_MODE_INFO'; payload: AnalysisModeInfo }
  | { type: 'INVALIDATE_ANALYSIS' }
  | { type: 'SET_MODE_WARNINGS'; payload: string[] }
  | { type: 'CLEAR_MODE_WARNINGS' }
  | { type: 'SET_MODE_TRANSITION_DATA'; payload: { fromMode: AnalysisMode; toMode: AnalysisMode; transitionType: string } | null }
  | { type: 'UPDATE_LAST_ANALYSIS_CONTEXT'; payload: { mode: AnalysisMode; roleHash: string; jdHash: string } }
  // Score multiplier and simulated CV actions (NEW for enhance.md)
  | { type: 'SET_SCORE_MULTIPLIERS'; payload: { cvMultiplier: number; atsMultiplier: number } }
  | { type: 'SET_SCORE_BREAKDOWNS'; payload: { cvBreakdown: Record<string, number> | null; atsBreakdown: Record<string, number> | null; cvPenaltyReasons?: string[] } }
  | { type: 'SET_ATS_SCORE_CONTEXT'; payload: 'jd-specific' | 'industry-general' }
  | { type: 'TOGGLE_SIMULATED_CV'; payload: boolean }
  | { type: 'SET_STRATEGIC_FIX_DATA'; payload: { strategicFix: any; authenticOpt: any; required: boolean; annotationLog: any[]; nextSteps: string[] } }
  // Document Formatting Actions
  | { type: 'SET_DATE_FORMAT'; payload: DateFormatStyle }
  | { type: 'SET_PAPER_SIZE'; payload: PaperSize }
  | { type: 'SET_JOB_SIDEBAR_OPEN'; payload: boolean }
  | { type: 'SET_TEMPLATE_OVERLAY_OPEN'; payload: boolean }
  | { type: 'SET_MORI_CHAT_MODE'; payload: boolean };

// Initial State
const initialState: ResumeEnhancerState = {
  mode: 'create',
  currentStep: 1,
  cvType: 'standalone',
  cvTitle: 'Untitled Resume',
  cvData: DEFAULT_UNIFIED_CV_DATA,
  selectedTemplate: null,
  targetRole: '',
  seniorityLevel: '',
  surgeonAnalysis: null,
  isAnalyzing: false,
  showProfilerModal: false,
  showSurgeonOverlay: false,
  showPreviewOverlay: false,
  cvScore: 0,
  surgicalFixes: [],
  fixAnnotations: [],
  reportOpen: false,
  reviewMode: false,
  activeFixId: undefined,
  isSaving: false,
  saveError: null,
  sessionStartTime: Date.now(),
  stepStartTimes: { 1: Date.now() },
  currentCVHash: undefined,
  suppressedFixHashes: [],
  // Career Ecosystem initial state
  isUserMaster: false,
  fresherMode: false,
  hasMasterCV: false,
  isFirstCVCreation: false,
  enforceMasterCVMode: false,
  atsScoreCap: 100,
  atsScore: 0,
  keywordGaps: [],
  keywordGapAnalysis: null,
  isAnalyzingKeywords: false,
  autoGeneratedCoverLetter: undefined,
  coverLetterId: undefined,
  jdText: '',
  jdWordCount: 0,
  analysisMode: 'insufficient-data',
  // Enhanced validation state (NEW)
  analysisModeInfo: null,
  lastAnalysisContext: null,
  modeTransitionWarnings: [],
  modeTransitionData: null,
  // Score multipliers and breakdowns (NEW for enhance.md)
  cvScoreMultiplier: 1.0,
  cvScoreBreakdown: null,
  cvPenaltyReasons: [],
  atsScoreMultiplier: 1.0,
  atsScoreBreakdown: null,
  atsScoreContext: 'industry-general',
  // Simulated CV toggle (NEW)
  showSimulatedCV: false,
  strategicFixAvailable: false,
  strategicFixData: null,
  authenticOptData: null,
  annotationLog: [],
  nextSteps: [],
  // Document Formatting Preferences
  dateFormat: 'MMM_YYYY',
  paperSize: 'A4',
  isJobSidebarOpen: false,
  isTemplateOverlayOpen: false,
  moriChatMode: false
};

// Reducer
function resumeEnhancerReducer(
  state: ResumeEnhancerState,
  action: ResumeEnhancerAction
): ResumeEnhancerState {
  switch (action.type) {
    case 'SET_JOB_SIDEBAR_OPEN':
      return { ...state, isJobSidebarOpen: action.payload };
    case 'SET_TEMPLATE_OVERLAY_OPEN':
      return { ...state, isTemplateOverlayOpen: action.payload };
    case 'SET_MORI_CHAT_MODE':
      return { ...state, moriChatMode: action.payload };
    case 'SET_MODE':
      return { ...state, mode: action.payload };

    case 'SET_STEP':
      return {
        ...state,
        currentStep: action.payload,
        stepStartTimes: {
          ...state.stepStartTimes,
          [action.payload]: Date.now()
        }
      };

    case 'SET_CURRENT_STEP':
      return {
        ...state,
        currentStep: action.payload,
        stepStartTimes: {
          ...state.stepStartTimes,
          [action.payload]: Date.now()
        }
      };

    case 'SET_CV_ID':
      return { ...state, cvId: action.payload };

    case 'SET_CV_TYPE':
      return { ...state, cvType: action.payload };

    case 'SET_CV_TITLE':
      return { ...state, cvTitle: action.payload };

    case 'UPDATE_CV_DATA':
      return {
        ...state,
        cvData: {
          ...state.cvData,
          ...action.payload
        }
      };

    case 'SET_CV_DATA':
      return { ...state, cvData: action.payload };

    case 'SET_TEMPLATE':
      return { ...state, selectedTemplate: action.payload };

    case 'SET_SELECTED_TEMPLATE':
      return { ...state, selectedTemplate: action.payload };

    case 'SET_ROLE_CONTEXT':
      return {
        ...state,
        targetRole: action.payload.targetRole,
        seniorityLevel: action.payload.seniorityLevel
      };

    case 'SET_TARGET_ROLE':
      return { ...state, targetRole: action.payload };

    case 'SET_SENIORITY_LEVEL':
      return { ...state, seniorityLevel: action.payload };

    case 'SET_JOB_DATA':
      return { ...state, jobData: action.payload };

    case 'SET_JOURNEY_ID':
      return { ...state, journeyId: action.payload };

    case 'CONVERT_TO_JOURNEY':
      return {
        ...state,
        cvType: 'journey',
        journeyId: action.payload.journeyId,
        jobData: action.payload.jobData,
        coverLetterId: action.payload.coverLetterId,
        autoGeneratedCoverLetter: action.payload.coverLetterDraft
      };

    case 'SET_SURGEON_ANALYSIS':
      return {
        ...state,
        surgeonAnalysis: action.payload,
        cvScore: action.payload.score || 0,
        surgicalFixes: (action.payload.fixes || []).map((f) => ({ ...f, status: f.status ?? 'pending' })),
        isAnalyzing: false
      };

    case 'SET_FIX_ANNOTATIONS':
      return { ...state, fixAnnotations: action.payload };

    case 'SET_REPORT_OPEN':
      return { ...state, reportOpen: action.payload };

    case 'SET_REVIEW_MODE':
      return { ...state, reviewMode: action.payload };

    case 'SET_ACTIVE_FIX':
      return { ...state, activeFixId: action.payload };

    case 'MARK_FIX_APPLIED':
      return {
        ...state,
        fixAnnotations: state.fixAnnotations.map((f) =>
          f.id === action.payload ? { ...f, status: 'applied' } : f
        ),
        surgicalFixes: (state.surgicalFixes || []).map((f) =>
          f.id === action.payload ? { ...f, status: 'accepted' } : f
        )
      };

    case 'MARK_FIX_DISMISSED':
      return {
        ...state,
        fixAnnotations: state.fixAnnotations.map((f) =>
          f.id === action.payload ? { ...f, status: 'dismissed' } : f
        ),
        surgicalFixes: (state.surgicalFixes || []).map((f) =>
          f.id === action.payload ? { ...f, status: 'rejected' } : f
        )
      };

    case 'MARK_FIX_SUPPRESSED':
      return {
        ...state,
        fixAnnotations: state.fixAnnotations.map((f) =>
          f.id === action.payload.fixId
            ? {
              ...f,
              status: 'suppressed',
              suppression: {
                timestamp: Date.now(),
                reason: action.payload.reason,
                userId: '' // Will be set by the service
              },
              fixSignatureHash: action.payload.fixSignatureHash
            }
            : f
        ),
        suppressedFixHashes: action.payload.fixSignatureHash
          ? [...state.suppressedFixHashes.filter(h => h !== action.payload.fixSignatureHash), action.payload.fixSignatureHash]
          : state.suppressedFixHashes
      };

    case 'MARK_FIX_SEMANTIC_MATCH':
      return {
        ...state,
        fixAnnotations: state.fixAnnotations.map((f) =>
          f.id === action.payload.fixId
            ? {
              ...f,
              status: 'semantic_match',
              semanticMatch: {
                requiredTerm: f.replacementText || f.originalText,
                foundTerm: action.payload.foundTerm,
                confidenceScore: action.payload.confidence
              }
            }
            : f
        )
      };

    case 'SET_ANALYZING':
      return { ...state, isAnalyzing: action.payload };

    case 'SET_SHOW_PROFILER_MODAL':
      return { ...state, showProfilerModal: action.payload };

    case 'SET_SHOW_SURGEON_OVERLAY':
      return { ...state, showSurgeonOverlay: action.payload };

    case 'SET_SHOW_PREVIEW_OVERLAY':
      return { ...state, showPreviewOverlay: action.payload };

    case 'APPLY_SURGICAL_FIX':
      return {
        ...state,
        surgicalFixes: (state.surgicalFixes || []).map((f) =>
          f.id === action.payload ? { ...f, status: 'accepted' } : f
        ),
        fixAnnotations: state.fixAnnotations.map((f) =>
          f.id === action.payload ? { ...f, status: 'applied' } : f
        )
      };

    case 'UPDATE_SURGICAL_FIX_STATUS':
      return {
        ...state,
        surgicalFixes: (state.surgicalFixes || []).map((f) =>
          f.id === action.payload.id ? { ...f, status: action.payload.status } : f
        )
      };

    case 'SET_SAVING':
      return { ...state, isSaving: action.payload };

    case 'SET_SAVE_ERROR':
      return { ...state, saveError: action.payload };

    case 'LOAD_CV':
      return {
        ...state,
        mode: 'edit',
        currentStep: 3, // Skip to builder/surgeon for editing
        cvId: action.payload.cvId,
        cvType: action.payload.cvType,
        cvTitle: action.payload.cvTitle,
        cvData: action.payload.cvData,
        selectedTemplate: action.payload.template || state.selectedTemplate,
        journeyId: action.payload.journeyId,
        jobData: action.payload.jobData,
        coverLetterId: action.payload.coverLetterId, // Load cover letter ID for journey CVs
        cvScore: 0,
        surgicalFixes: [],
        showPreviewOverlay: false,
        showSurgeonOverlay: false,
        showProfilerModal: false,
        // Reset report state when switching CVs
        fixAnnotations: [],
        reportOpen: false,
        reviewMode: false,
        activeFixId: undefined
      };

    case 'RESET_STATE':
      return {
        ...initialState,
        sessionStartTime: Date.now(),
        stepStartTimes: { 1: Date.now() },
        currentCVHash: undefined,
        suppressedFixHashes: []
      };

    // Career Ecosystem Actions
    case 'SET_IS_USER_MASTER':
      return { ...state, isUserMaster: action.payload };

    case 'SET_FRESHER_MODE':
      return { ...state, fresherMode: action.payload };

    case 'SET_HAS_MASTER_CV':
      return { ...state, hasMasterCV: action.payload };

    case 'SET_IS_FIRST_CV_CREATION':
      return { ...state, isFirstCVCreation: action.payload };

    case 'SET_ENFORCE_MASTER_CV_MODE':
      // When enforcing master CV mode, also set cvType to master
      return {
        ...state,
        enforceMasterCVMode: action.payload,
        cvType: action.payload ? 'master' : state.cvType
      };

    case 'SET_ATS_SCORE_CAP':
      return { ...state, atsScoreCap: action.payload };

    case 'SET_ATS_SCORE':
      return { ...state, atsScore: Math.min(action.payload, state.atsScoreCap) };

    case 'SET_KEYWORD_GAPS':
      return { ...state, keywordGaps: action.payload };

    case 'SET_KEYWORD_GAP_ANALYSIS':
      return {
        ...state,
        keywordGapAnalysis: action.payload,
        keywordGaps: action.payload?.gaps || [],
        atsScore: action.payload ? Math.min(action.payload.matchScore, state.atsScoreCap) : state.atsScore,
        isAnalyzingKeywords: false
      };

    case 'SET_ANALYZING_KEYWORDS':
      return { ...state, isAnalyzingKeywords: action.payload };

    case 'UPDATE_KEYWORD_GAP':
      return {
        ...state,
        keywordGaps: state.keywordGaps.map((gap) =>
          gap.keyword === action.payload.keyword
            ? { ...gap, ...action.payload.updates }
            : gap
        )
      };

    case 'SET_AUTO_COVER_LETTER':
      return {
        ...state,
        autoGeneratedCoverLetter: action.payload.draft,
        coverLetterId: action.payload.coverLetterId || state.coverLetterId
      };

    case 'SET_JD_TEXT':
      const wordCount = action.payload.trim().split(/\s+/).filter(Boolean).length;
      return {
        ...state,
        jdText: action.payload,
        jdWordCount: wordCount
      };

    case 'CLEAR_JD_TEXT':
      return {
        ...state,
        jdText: '',
        jdWordCount: 0
      };

    // Validation Actions (NEW)
    case 'SET_ANALYSIS_MODE_INFO':
      return {
        ...state,
        analysisModeInfo: action.payload,
        analysisMode: action.payload.mode
      };

    case 'INVALIDATE_ANALYSIS':
      return {
        ...state,
        surgeonAnalysis: null,
        cvScore: 0,
        surgicalFixes: [],
        fixAnnotations: []
      };

    case 'SET_MODE_WARNINGS':
      return { ...state, modeTransitionWarnings: action.payload };

    case 'CLEAR_MODE_WARNINGS':
      return { ...state, modeTransitionWarnings: [] };

    case 'SET_MODE_TRANSITION_DATA':
      return { ...state, modeTransitionData: action.payload };

    case 'UPDATE_LAST_ANALYSIS_CONTEXT':
      return {
        ...state,
        lastAnalysisContext: action.payload
      };

    // Score multiplier and simulated CV actions (NEW for enhance.md)
    case 'SET_SCORE_MULTIPLIERS':
      return {
        ...state,
        cvScoreMultiplier: action.payload.cvMultiplier,
        atsScoreMultiplier: action.payload.atsMultiplier
      };

    case 'SET_SCORE_BREAKDOWNS':
      return {
        ...state,
        cvScoreBreakdown: action.payload.cvBreakdown,
        atsScoreBreakdown: action.payload.atsBreakdown,
        cvPenaltyReasons: action.payload.cvPenaltyReasons || []
      };

    case 'SET_ATS_SCORE_CONTEXT':
      return {
        ...state,
        atsScoreContext: action.payload
      };

    case 'TOGGLE_SIMULATED_CV':
      return {
        ...state,
        showSimulatedCV: action.payload
      };

    case 'SET_STRATEGIC_FIX_DATA':
      return {
        ...state,
        strategicFixData: action.payload.strategicFix,
        authenticOptData: action.payload.authenticOpt,
        strategicFixAvailable: action.payload.required,
        annotationLog: action.payload.annotationLog || [],
        nextSteps: action.payload.nextSteps || []
      };

    // Document Formatting Actions
    case 'SET_DATE_FORMAT':
      return {
        ...state,
        dateFormat: action.payload
      };

    case 'SET_PAPER_SIZE':
      return {
        ...state,
        paperSize: action.payload
      };

    default:
      return state;
  }
}

// Context
interface ResumeEnhancerContextType {
  state: ResumeEnhancerState;
  dispatch: React.Dispatch<ResumeEnhancerAction>;

  // Helper functions
  goToStep: (step: 1 | 2 | 3 | 4 | 5) => void;
  nextStep: () => void;
  prevStep: () => void;
  runCVSurgeon: () => Promise<{ score: number; fixes: SurgicalFix[]; annotations: FixAnnotation[] } | null>;
  updateCVData: (data: Partial<UnifiedCVDataStructure>) => void;
  setTemplate: (template: ITemplate) => void;
  setRoleContext: (role: string, seniority: string) => void;
  convertToJourney: (journeyId: string, jobData: any, coverLetterId?: string, coverLetterDraft?: string) => void;
  loadCV: (cvData: { cvId: string; cvType: 'master' | 'journey' | 'standalone'; cvTitle: string; cvData: UnifiedCVDataStructure; template?: ITemplate; journeyId?: string; jobData?: any; coverLetterId?: string }) => void;
  resetState: () => void;

  // Career Ecosystem helper functions
  setJdText: (text: string) => void;
  clearJdText: () => void;
  setFresherMode: (isFresher: boolean) => void;
  setAtsScoreCap: (cap: number) => void;
  setKeywordGaps: (gaps: KeywordGap[]) => void;
  updateKeywordGap: (keyword: string, updates: Partial<KeywordGap>) => void;
  detectFresherMode: () => boolean;
  determineCVType: () => 'master' | 'journey' | 'standalone';
  getAnalysisModeInfo: () => AnalysisModeResult;
  // Phase 3 view controls
  setJobSidebarOpen: (isOpen: boolean) => void;
  setTemplateOverlayOpen: (isOpen: boolean) => void;
  // Enhanced validation helpers (NEW)
  getAnalysisModeWithWarnings: () => AnalysisModeInfo;
  validateAndSetJD: (text: string) => void;
  validateAndSetRole: (role: string, seniority: string) => void;
  invalidateAnalysisIfNeeded: () => void;
}

const ResumeEnhancerContext = createContext<ResumeEnhancerContextType | null>(null);

// Provider
export function ResumeEnhancerProvider({ children }: { children: ReactNode }) {
  const [state, dispatch] = useReducer(resumeEnhancerReducer, initialState);

  // Helper functions
  const goToStep = React.useCallback((step: 1 | 2 | 3 | 4 | 5) => {
    dispatch({ type: 'SET_STEP', payload: step });
  }, []);

  const nextStep = React.useCallback(() => {
    dispatch({ type: 'SET_STEP', payload: (Math.min(5, (state.currentStep + 1)) as 1 | 2 | 3 | 4 | 5) });
  }, [state.currentStep]);

  const prevStep = React.useCallback(() => {
    dispatch({ type: 'SET_STEP', payload: (Math.max(1, (state.currentStep - 1)) as 1 | 2 | 3 | 4 | 5) });
  }, [state.currentStep]);

  const runCVSurgeon = React.useCallback(async () => {
    if (!state.targetRole || !state.seniorityLevel) return null;
    dispatch({ type: 'SET_ANALYZING', payload: true });
    try {
      const result = await CVSurgeonService.analyzeCV(
        state.cvData,
        state.targetRole,
        state.seniorityLevel,
        state.jobData
      );
      dispatch({ type: 'SET_SURGEON_ANALYSIS', payload: { score: result.score, fixes: result.fixes } });
      dispatch({ type: 'SET_FIX_ANNOTATIONS', payload: result.annotations });
      return result;
    } catch (e) {
      dispatch({ type: 'SET_ANALYZING', payload: false });
      throw e;
    }
  }, [state.targetRole, state.seniorityLevel, state.cvData, state.jobData]);

  const updateCVData = React.useCallback((data: Partial<UnifiedCVDataStructure>) => {
    dispatch({ type: 'UPDATE_CV_DATA', payload: data });
  }, []);

  const setTemplate = React.useCallback((template: ITemplate) => {
    dispatch({ type: 'SET_TEMPLATE', payload: template });
  }, []);

  const setRoleContext = React.useCallback((role: string, seniority: string) => {
    dispatch({ type: 'SET_ROLE_CONTEXT', payload: { targetRole: role, seniorityLevel: seniority } });
  }, []);

  const convertToJourney = React.useCallback((journeyId: string, jobData: any, coverLetterId?: string, coverLetterDraft?: string) => {
    dispatch({ type: 'CONVERT_TO_JOURNEY', payload: { journeyId, jobData, coverLetterId, coverLetterDraft } });
  }, []);

  const loadCV = React.useCallback((cvData: { cvId: string; cvType: 'master' | 'journey' | 'standalone'; cvTitle: string; cvData: UnifiedCVDataStructure; template?: ITemplate; journeyId?: string; jobData?: any; coverLetterId?: string }) => {
    dispatch({ type: 'LOAD_CV', payload: cvData });
  }, []);

  const resetState = React.useCallback(() => {
    dispatch({ type: 'RESET_STATE' });
  }, []);

  // Career Ecosystem helper functions
  const setJdText = React.useCallback((text: string) => {
    dispatch({ type: 'SET_JD_TEXT', payload: text });
  }, []);

  const clearJdText = React.useCallback(() => {
    dispatch({ type: 'CLEAR_JD_TEXT' });
  }, []);

  const setFresherMode = React.useCallback((isFresher: boolean) => {
    dispatch({ type: 'SET_FRESHER_MODE', payload: isFresher });
  }, []);

  const setAtsScoreCap = React.useCallback((cap: number) => {
    dispatch({ type: 'SET_ATS_SCORE_CAP', payload: cap });
  }, []);

  const setKeywordGaps = React.useCallback((gaps: KeywordGap[]) => {
    dispatch({ type: 'SET_KEYWORD_GAPS', payload: gaps });
  }, []);

  const updateKeywordGap = React.useCallback((keyword: string, updates: Partial<KeywordGap>) => {
    dispatch({ type: 'UPDATE_KEYWORD_GAP', payload: { keyword, updates } });
  }, []);

  /**
   * Phase 3 View Controls
   */
  const setJobSidebarOpen = React.useCallback((isOpen: boolean) => {
    dispatch({ type: 'SET_JOB_SIDEBAR_OPEN', payload: isOpen });
  }, []);

  const setTemplateOverlayOpen = React.useCallback((isOpen: boolean) => {
    dispatch({ type: 'SET_TEMPLATE_OVERLAY_OPEN', payload: isOpen });
  }, []);

  /**
   * Detect if the current CV data indicates "Fresher Mode"
   * (no meaningful work experience - should focus on Education/Projects)
   */
  const detectFresherMode = React.useCallback((): boolean => {
    const work = state.cvData.work;
    if (!work || !Array.isArray(work) || work.length === 0) {
      return true;
    }
    // Check if work entries have meaningful content
    const hasValidWork = work.some((w: any) =>
      w && (w.name || w.company || w.position)
    );
    return !hasValidWork;
  }, [state.cvData.work]);

  /**
   * Determine the appropriate CV type based on current state
   * - Has JD text → Journey
   * - No Master exists + first CV → Master
   * - Otherwise → Standalone
   */
  const determineCVType = React.useCallback((): 'master' | 'journey' | 'standalone' => {
    // If JD text is provided, this is a Journey CV
    if (state.jdText && state.jdWordCount >= 10) {
      return 'journey';
    }
    // If user doesn't have a Master CV yet, make this the Master
    if (!state.hasMasterCV) {
      return 'master';
    }
    // Default to Standalone
    return 'standalone';
  }, [state.jdText, state.jdWordCount, state.hasMasterCV]);

  /**
   * Get current analysis mode information
   * This determines how CV analysis should be performed
   */
  const getAnalysisModeInfo = React.useCallback((): AnalysisModeResult => {
    return getAnalysisMode(
      state.cvType,
      state.targetRole,
      state.seniorityLevel,
      state.jdText || state.jobData?.description || state.jobData?.jd
    );
  }, [state.cvType, state.targetRole, state.seniorityLevel, state.jdText, state.jobData]);

  /**
   * Get enhanced analysis mode with validation and warnings (NEW)
   */
  const getAnalysisModeWithWarnings = React.useCallback((): AnalysisModeInfo => {
    return getAnalysisModeWithValidation(
      state.cvType,
      state.targetRole,
      state.seniorityLevel,
      state.jdText || state.jobData?.description || state.jobData?.jd,
      state.jobData
    );
  }, [state.cvType, state.targetRole, state.seniorityLevel, state.jdText, state.jobData]);

  /**
   * Validate and set JD text with automatic sanitization (NEW)
   */
  const validateAndSetJD = React.useCallback((text: string) => {
    const currentModeInfo = getAnalysisModeWithWarnings();
    dispatch({ type: 'SET_JD_TEXT', payload: text });

    // Check if this changes the analysis mode
    const newModeInfo = getAnalysisModeWithValidation(
      state.cvType,
      state.targetRole,
      state.seniorityLevel,
      text,
      state.jobData
    );

    if (hasAnalysisContextChanged(currentModeInfo, newModeInfo)) {
      dispatch({ type: 'INVALIDATE_ANALYSIS' });
      if (newModeInfo.warnings.length > 0) {
        dispatch({ type: 'SET_MODE_WARNINGS', payload: newModeInfo.warnings });
      }
    }

    dispatch({ type: 'SET_ANALYSIS_MODE_INFO', payload: newModeInfo });
  }, [state.cvType, state.targetRole, state.seniorityLevel, state.jobData, getAnalysisModeWithWarnings]);

  /**
   * Validate and set role with automatic confidence check (NEW)
   */
  const validateAndSetRole = React.useCallback((role: string, seniority: string) => {
    const currentModeInfo = getAnalysisModeWithWarnings();
    setRoleContext(role, seniority);

    // Check if this changes the analysis mode
    const newModeInfo = getAnalysisModeWithValidation(
      state.cvType,
      role,
      seniority,
      state.jdText || state.jobData?.description || state.jobData?.jd,
      state.jobData
    );

    if (hasAnalysisContextChanged(currentModeInfo, newModeInfo)) {
      dispatch({ type: 'INVALIDATE_ANALYSIS' });
      if (newModeInfo.warnings.length > 0) {
        dispatch({ type: 'SET_MODE_WARNINGS', payload: newModeInfo.warnings });
      }
    }

    dispatch({ type: 'SET_ANALYSIS_MODE_INFO', payload: newModeInfo });
  }, [state.cvType, state.jdText, state.jobData, getAnalysisModeWithWarnings, setRoleContext]);

  /**
   * Check if analysis should be invalidated based on context changes (NEW)
   */
  const invalidateAnalysisIfNeeded = React.useCallback(() => {
    if (!state.lastAnalysisContext) return;

    const currentInfo = getAnalysisModeWithWarnings();
    if (hasAnalysisContextChanged(state.analysisModeInfo, currentInfo)) {
      dispatch({ type: 'INVALIDATE_ANALYSIS' });
      dispatch({ type: 'SET_ANALYSIS_MODE_INFO', payload: currentInfo });
    }
  }, [state.lastAnalysisContext, state.analysisModeInfo, getAnalysisModeWithWarnings]);

  const contextValue: ResumeEnhancerContextType = React.useMemo(() => ({
    state,
    dispatch,
    goToStep,
    nextStep,
    prevStep,
    runCVSurgeon,
    updateCVData,
    setTemplate,
    setRoleContext,
    convertToJourney,
    loadCV,
    resetState,
    // Career Ecosystem helpers
    setJdText,
    clearJdText,
    setFresherMode,
    setAtsScoreCap,
    setKeywordGaps,
    updateKeywordGap,
    detectFresherMode,
    determineCVType,
    getAnalysisModeInfo,
    // Phase 3 view controls
    setJobSidebarOpen,
    setTemplateOverlayOpen,
    // Enhanced validation helpers (NEW)
    getAnalysisModeWithWarnings,
    validateAndSetJD,
    validateAndSetRole,
    invalidateAnalysisIfNeeded
  }), [
    state,
    dispatch,
    goToStep,
    nextStep,
    prevStep,
    runCVSurgeon,
    updateCVData,
    setTemplate,
    setRoleContext,
    convertToJourney,
    loadCV,
    resetState,
    setJdText,
    clearJdText,
    setFresherMode,
    setAtsScoreCap,
    setKeywordGaps,
    updateKeywordGap,
    detectFresherMode,
    determineCVType,
    getAnalysisModeInfo,
    setJobSidebarOpen,
    setTemplateOverlayOpen,
    getAnalysisModeWithWarnings,
    validateAndSetJD,
    validateAndSetRole,
    invalidateAnalysisIfNeeded
  ]);

  return (
    <ResumeEnhancerContext.Provider value={contextValue}>
      {children}
    </ResumeEnhancerContext.Provider>
  );
}

// Hook to use context
export function useResumeEnhancer() {
  const context = useContext(ResumeEnhancerContext);
  if (!context) {
    throw new Error('useResumeEnhancer must be used within ResumeEnhancerProvider');
  }
  return context;
}
