'use client';

import React from 'react';
import {
  Target, CheckCircle2, AlertTriangle, Clock, RefreshCw, Sparkles,
  Building, Briefcase, Sliders, Check
} from 'lucide-react';
import { useResumeEnhancer } from '@/contexts/ResumeEnhancerContext';
import { AnimatedScore, AnimatedProgressBar } from '@/components/ui/AnimatedScore';

interface CoverLetterDesignProps {
  fontSize: number;
  lineHeight: number;
  pageMargin: number;
  accentColor: string;
  fontFamily: 'font-sans' | 'font-serif' | 'font-mono';
}

interface LetterGuidePanelProps {
  onUpdateTarget?: () => void;
  matchScore?: number;
  onComplete?: () => void;
  
  // Mori Chat toggle
  showMoriChat?: boolean;
  onToggleMoriChat?: () => void;
  
  // Design properties
  templateType: 'classic' | 'modern' | 'minimal' | 'typographic' | 'column-split' | 'accent-banner' | 'creative-edge' | 'executive-slate';
  setTemplateType: (type: 'classic' | 'modern' | 'minimal' | 'typographic' | 'column-split' | 'accent-banner' | 'creative-edge' | 'executive-slate') => void;
  design: CoverLetterDesignProps;
  setDesign: React.Dispatch<React.SetStateAction<CoverLetterDesignProps>>;
  isEditing: boolean;
  setIsEditing: (editing: boolean) => void;
}

export const LetterGuidePanel: React.FC<LetterGuidePanelProps> = ({
  onUpdateTarget,
  matchScore = 82,
  templateType,
  setTemplateType,
  design,
  setDesign,
  isEditing,
  setIsEditing,
  onComplete,
  showMoriChat,
  onToggleMoriChat
}) => {
  const { state, setJobSidebarOpen } = useResumeEnhancer();

  // Score calculations
  const score = matchScore;
  const grade = score >= 90 ? 'A' : score >= 80 ? 'B' : score >= 70 ? 'C' : score >= 60 ? 'D' : 'F';
  const gradeColor = score >= 80 ? 'text-emerald-500' : score >= 65 ? 'text-yellow-500' : 'text-rose-500';
  const strokeColor = score >= 80 ? '#10b981' : score >= 65 ? '#F59E0B' : '#F43F5E';

  const arcRadius = 44;
  const totalCircumference = 2 * Math.PI * arcRadius;
  const strokeDashoffset = totalCircumference - (score / 100) * totalCircumference;

  // Dynamic analysis of cover letter content
  const letterText = state.autoGeneratedCoverLetter || '';
  const wordCount = letterText.trim().split(/\s+/).filter(Boolean).length;
  
  const hasCompany = state.jobData?.company && letterText.toLowerCase().includes(state.jobData.company.toLowerCase());
  const hasRole = state.targetRole && letterText.toLowerCase().includes(state.targetRole.toLowerCase());
  const numberRegex = /\b\d+(?:%|\s*years|k)?\b/g;
  const numberMatches = letterText.match(numberRegex);
  const email = state.cvData?.basics?.email;
  const phone = state.cvData?.basics?.phone;

  // Metric breakdown based on actual content
  const metrics = [
    { label: 'Role Alignment', value: hasRole ? Math.min(100, Math.round(score * 1.05)) : Math.round(score * 0.8) },
    { label: 'Impact & Value', value: (numberMatches && numberMatches.length >= 2) ? Math.min(100, Math.round(score * 1.05)) : Math.round(score * 0.8) },
    { label: 'Clarity & Flow', value: (wordCount >= 200 && wordCount <= 450) ? Math.min(100, Math.round(score * 1.02)) : Math.round(score * 0.9) },
    { label: 'Tone Suitability', value: Math.min(100, Math.round(score * 1.02)) },
    { label: 'ATS Friendliness', value: (hasCompany && hasRole) ? Math.min(100, Math.round(score * 1.02)) : Math.round(score * 0.85) }
  ];

  const strengths: string[] = [];
  const warnings: string[] = [];

  // 1. Check target role and company citation
  if (hasCompany && hasRole) {
    strengths.push(`Successfully cites target role (${state.targetRole}) and company (${state.jobData.company}).`);
  } else if (hasCompany) {
    strengths.push(`Mentions the company (${state.jobData.company}) in the letter body.`);
    if (state.targetRole) {
      warnings.push(`Target role (${state.targetRole}) is not explicitly mentioned in the text.`);
    }
  } else if (hasRole) {
    strengths.push(`Mentions the target role (${state.targetRole}) in the letter body.`);
    if (state.jobData?.company) {
      warnings.push(`Target company (${state.jobData.company}) is not explicitly mentioned in the text.`);
    }
  } else {
    if (state.targetRole || state.jobData?.company) {
      warnings.push("Ensure your opening paragraph explicitly mentions the target role and company.");
    }
  }

  // 2. Check for metrics/quantifiable achievements
  if (numberMatches && numberMatches.length >= 2) {
    strengths.push(`Includes ${numberMatches.length} quantifiable achievements or metrics, adding credibility.`);
  } else {
    warnings.push("Could incorporate more quantifiable achievements (e.g. percentages, scale, or metrics).");
  }

  // 3. Check contact info completeness
  if (email && phone) {
    strengths.push("Header contact details (email and phone number) are fully populated.");
  } else {
    const missing = [];
    if (!email) missing.push("email");
    if (!phone) missing.push("phone number");
    warnings.push(`Ensure contact details (${missing.join(' and ')}) are populated in the header.`);
  }

  // 4. Check word count suitability
  if (wordCount > 0) {
    if (wordCount < 200) {
      warnings.push(`The letter is a bit short (${wordCount} words). Industry standard is 250-400 words.`);
    } else if (wordCount > 450) {
      warnings.push(`The letter is long (${wordCount} words). Try keeping it concise and strictly under one page.`);
    } else {
      strengths.push(`Excellent letter length (${wordCount} words), fitting cleanly on a single page.`);
    }
  } else {
    warnings.push("No cover letter body content. Generate one using AI or start writing.");
  }

  // Fill in placeholders if lists are empty
  if (strengths.length === 0) {
    strengths.push("Structure is ready to populate with tailored career experience details.");
  }
  if (warnings.length === 0) {
    warnings.push("No critical enhancements suggested. Your cover letter looks solid!");
  }

  const readTimeSeconds = Math.max(10, Math.round((wordCount / 200) * 60));
  const readTimeText = readTimeSeconds >= 60 
    ? `${Math.floor(readTimeSeconds / 60)}m ${readTimeSeconds % 60}s Read Time`
    : `${readTimeSeconds}s Read Time`;

  return (
    <div className="flex flex-col h-full bg-white dark:bg-[#141810] border border-gray-200 dark:border-white/5 rounded-2xl shadow-sm overflow-hidden">
      
      {/* Header Bar */}
      <div className="px-4 py-2.5 border-b border-gray-200 dark:border-white/10 flex items-center justify-between bg-white dark:bg-transparent shrink-0">
        <div className="flex items-center gap-2 text-xs font-bold text-slate-700 dark:text-slate-300">
          <Sliders className="w-4 h-4 text-emerald-500" />
          <span>Letter Guide</span>
        </div>
        {onToggleMoriChat && (
          <button 
             onClick={onToggleMoriChat}
             className={`px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider rounded-md border transition-all flex items-center gap-1.5 ${
               showMoriChat 
                 ? 'bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-500/20' 
                 : 'bg-gray-50 hover:bg-gray-100 dark:bg-white/5 border-gray-200 dark:border-white/10 text-gray-500 hover:text-gray-700 dark:hover:text-gray-300'
             }`}
          >
             <Sparkles className="w-3.5 h-3.5 animate-pulse" />
             {showMoriChat ? 'Close Mori' : 'Ask Mori'}
          </button>
        )}
      </div>

      {/* Tabs Content */}
      <div className="flex-1 overflow-y-auto custom-scrollbar p-5">
        <div className="flex flex-col gap-6">
          {/* 1. OVERALL SCORE */}
            <div className="flex flex-col bg-gray-50 dark:bg-white/[0.02] border border-gray-150 dark:border-white/[0.04] rounded-xl p-4 transition-all hover:bg-gray-100/50 dark:hover:bg-white/[0.04]">
              <div className="text-[10px] font-black uppercase tracking-widest text-gray-400 mb-3 flex items-center justify-between">
                <span>Overall Letter Grade</span>
                <span className="flex items-center gap-1 text-emerald-500 font-bold"><Sparkles size={10} /> Live Coaching</span>
              </div>
              
              <div className="flex items-center gap-4">
                <div className="relative w-[80px] h-[80px] shrink-0 flex items-center justify-center">
                  <svg className="w-full h-full -rotate-90" viewBox="0 0 100 100">
                    <circle cx="50" cy="50" r={arcRadius} fill="none" stroke="currentColor" strokeWidth="7" className="text-gray-200 dark:text-white/5" />
                    <circle
                      cx="50" cy="50" r={arcRadius} fill="none" stroke={strokeColor} strokeWidth="7"
                      strokeDasharray={totalCircumference} strokeDashoffset={strokeDashoffset} strokeLinecap="round"
                      style={{ filter: `drop-shadow(0 0 4px ${strokeColor}40)` }}
                      className="transition-all duration-1000 ease-out"
                    />
                  </svg>
                  <div className="absolute inset-0 flex flex-col items-center justify-center">
                    <AnimatedScore value={score} size="sm" className="text-2xl font-black tracking-tighter text-gray-900 dark:text-white leading-none" />
                    <span className="text-[9px] font-bold uppercase tracking-widest text-gray-400 mt-0.5">/ 100</span>
                  </div>
                </div>

                <div className="min-w-0">
                  <div className="flex items-center gap-2 mb-0.5">
                    <span className={`text-xl font-black ${gradeColor}`}>{grade} Grade</span>
                  </div>
                  <p className="text-[10px] font-bold text-gray-500 uppercase tracking-wide">
                    {score >= 80 ? 'Tailored & Optimized' : score >= 65 ? 'Ready to Enhance' : 'Needs Tailoring'}
                  </p>
                  <div className="text-[9px] font-bold text-blue-500 flex items-center gap-1 mt-1">
                    <Clock size={10} /> {readTimeText}
                  </div>
                </div>
              </div>
            </div>

            {/* 2. TARGET CONTEXT */}
            <div className="bg-gray-50 dark:bg-white/[0.02] border border-gray-150 dark:border-white/[0.04] rounded-xl p-4 flex flex-col gap-3">
              <div className="flex items-center justify-between">
                <h4 className="text-[10px] font-black text-gray-400 uppercase tracking-widest flex items-center gap-1.5">
                  <Target className="w-3.5 h-3.5 text-[#80FF00]" />
                  Target Context
                </h4>
                <div className="flex items-center gap-1 px-2 py-0.5 rounded-full bg-[#80FF00]/10 border border-[#80FF00]/20 text-[9px] font-black text-[#80FF00] uppercase italic">
                  {score}% Match
                </div>
              </div>

              <div className="flex flex-col gap-1.5">
                <div className="text-xs font-black text-gray-900 dark:text-white uppercase tracking-tight flex items-center gap-1.5 truncate">
                  <Briefcase size={12} className="text-gray-400 shrink-0" />
                  {state.targetRole || 'Target Position Not Set'}
                </div>
                <div className="text-[10px] font-bold text-gray-500 flex items-center gap-1.5 truncate">
                  <Building size={12} className="text-gray-400 shrink-0" />
                  {state.jobData?.company || 'Unknown Company'}
                  {state.jobData && <CheckCircle2 size={10} className="text-[#80FF00]" />}
                </div>
              </div>

              <button 
                onClick={onUpdateTarget || (() => setJobSidebarOpen?.(true))}
                className="w-full mt-1 py-1.5 bg-gray-900 hover:bg-gray-800 dark:bg-white/10 dark:hover:bg-white/15 text-white dark:text-white text-[10px] font-black uppercase tracking-widest rounded-lg transition-all flex items-center justify-center gap-1.5"
              >
                <RefreshCw size={10} /> Update Target Job
              </button>
            </div>

            {/* 3. STRENGTH METRICS */}
            <div className="flex flex-col gap-3">
              <h4 className="text-[10px] font-black text-gray-400 uppercase tracking-widest">Analysis Metrics</h4>
              <div className="flex flex-col gap-3">
                {metrics.map((metric) => (
                  <div key={metric.label} className="flex flex-col gap-1.5">
                    <div className="flex justify-between items-center text-[10px] font-bold uppercase tracking-wider text-gray-500 dark:text-gray-400">
                      <span>{metric.label}</span>
                      <span className="text-emerald-500">{metric.value}%</span>
                    </div>
                    <AnimatedProgressBar
                      value={metric.value}
                      height={6}
                      colorStops={[
                        { threshold: 0, color: '#F43F5E' },
                        { threshold: 60, color: '#F59E0B' },
                        { threshold: 80, color: '#10b981' },
                      ]}
                    />
                  </div>
                ))}
              </div>
            </div>

            {/* 4. INSIGHTS LIST */}
            <div className="border-t border-gray-200 dark:border-white/5 pt-4 flex flex-col gap-4">
              <div>
                <h4 className="text-[10px] font-black text-emerald-500 uppercase tracking-widest mb-2 flex items-center gap-1">
                  <CheckCircle2 size={12} /> Key Strengths
                </h4>
                <ul className="flex flex-col gap-2">
                  {strengths.map((str, index) => (
                    <li key={index} className="text-[11px] font-medium text-gray-600 dark:text-gray-400 leading-relaxed pl-4 relative">
                      <span className="absolute left-0 top-1.5 w-1.5 h-1.5 rounded-full bg-emerald-500" />
                      {str}
                    </li>
                  ))}
                </ul>
              </div>
              <div>
                <h4 className="text-[10px] font-black text-amber-500 uppercase tracking-widest mb-2 flex items-center gap-1">
                  <AlertTriangle size={12} /> Optimization Opportunities
                </h4>
                <ul className="flex flex-col gap-2">
                  {warnings.map((warn, index) => (
                    <li key={index} className="text-[11px] font-medium text-gray-600 dark:text-gray-400 leading-relaxed pl-4 relative">
                      <span className="absolute left-0 top-1.5 w-1.5 h-1.5 rounded-full bg-amber-500" />
                      {warn}
                    </li>
                  ))}
                </ul>
              </div>
           </div>
         </div>
       </div>

      {onComplete && (
        <div className="p-4 border-t border-gray-200 dark:border-white/5 bg-gray-50/50 dark:bg-white/[0.02] shrink-0">
          <button 
            onClick={onComplete}
            className="w-full py-3 bg-[#80FF00] hover:bg-[#99ff33] text-black text-xs font-black uppercase tracking-widest rounded-xl transition-all flex items-center justify-center gap-1.5 shadow-md shadow-emerald-500/10 active:scale-[0.98]"
            title="Review & Export"
          >
            Review & Export <Check className="w-4 h-4" />
          </button>
        </div>
      )}

    </div>
  );
};

export default LetterGuidePanel;
