'use client';

import React, { useState, useEffect, useRef, useCallback } from 'react';
import { useResumeEnhancer } from '@/contexts/ResumeEnhancerContext';
import { MoriMessageBubble, MoriLoadingIndicator, MoriSuggestionChips } from '@/components/mori';
import { 
  Send, Trash2, MousePointer2, MessageSquare, History, Edit2, X, Plus, Check
} from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import toast from '@/lib/hot-toast';

interface SuggestedImprovement {
  original: string;
  improved: string;
  isSelection: boolean;
}

interface Message {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: number;
  selection?: {
    text: string;
  };
  suggestion?: SuggestedImprovement;
  isError?: boolean;
}

interface ChatHistoryItem {
  id: string;
  title: string;
  updatedAt: number;
  messages: Message[];
}

const SUGGESTIONS = [
  { label: '✨ Improve Tone', prompt: 'Improve the overall tone to be professional, confident, and persuasive.' },
  { label: '🎯 Align with JD', prompt: 'Align this content to address the core requirements in the job description.' },
  { label: '🚀 Highlight Achievements', prompt: 'Strengthen the text by emphasizing tangible achievements and impact.' },
  { label: '✂️ Make Shorter', prompt: 'Shorten and condense the content to make it more direct and concise.' }
];

interface MoriCoverLetterChatProps {
  onBodyChange?: (content: string) => void;
  onClose?: () => void;
}

export const MoriCoverLetterChat: React.FC<MoriCoverLetterChatProps> = ({
  onBodyChange,
  onClose
}) => {
  const { state, dispatch } = useResumeEnhancer();
  const [input, setInput] = useState('');
  const [messages, setMessages] = useState<Message[]>([
    {
      id: 'welcome',
      role: 'assistant',
      content: "Hi! I'm Mori. I can help you polish and write your cover letter. Highlight any paragraph or sentence on the left, then choose a quick action or tell me what to change.",
      timestamp: Date.now()
    }
  ]);
  const [isLoading, setIsLoading] = useState(false);
  const [currentSelection, setCurrentSelection] = useState<{ text: string } | null>(null);
  
  // History State
  const [chatId, setChatId] = useState<string | null>(null);
  const [chatHistory, setChatHistory] = useState<ChatHistoryItem[]>([]);
  const [showHistory, setShowHistory] = useState(false);
  const [editingChatId, setEditingChatId] = useState<string | null>(null);
  const [editTitle, setEditTitle] = useState('');

  const scrollRef = useRef<HTMLDivElement>(null);

  // Load chats from localStorage
  useEffect(() => {
    try {
      const saved = localStorage.getItem('mori_cl_chat_history');
      if (saved) {
        setChatHistory(JSON.parse(saved));
      }
    } catch (e) {
      console.error('Failed to load cover letter chat history from localStorage', e);
    }
  }, []);

  // Save chats to localStorage
  const saveToHistory = (updatedHistory: ChatHistoryItem[]) => {
    setChatHistory(updatedHistory);
    try {
      localStorage.setItem('mori_cl_chat_history', JSON.stringify(updatedHistory));
    } catch (e) {
      console.error('Failed to save chat history', e);
    }
  };

  // Auto-scroll to bottom
  useEffect(() => {
    if (scrollRef.current && !showHistory) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [messages, isLoading, showHistory, currentSelection]);

  // Listen for selection text in the window
  useEffect(() => {
    const handleMouseUp = () => {
      const selection = window.getSelection()?.toString().trim();
      if (selection && selection.length > 5) {
        setCurrentSelection({ text: selection });
      }
    };

    const handleMouseDown = () => {
      setTimeout(() => {
        const selection = window.getSelection()?.toString().trim();
        if (!selection) {
          setCurrentSelection(null);
        }
      }, 200);
    };

    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape' && currentSelection) {
        setCurrentSelection(null);
      }
    };

    document.addEventListener('mouseup', handleMouseUp);
    document.addEventListener('mousedown', handleMouseDown);
    window.addEventListener('keydown', handleKeyDown);
    return () => {
      document.removeEventListener('mouseup', handleMouseUp);
      document.removeEventListener('mousedown', handleMouseDown);
      window.removeEventListener('keydown', handleKeyDown);
    };
  }, [currentSelection]);

  const handleSend = async (overrideInput?: string) => {
    const textToSend = overrideInput || input;
    if (!textToSend.trim() || isLoading) return;

    const bodyContent = state.autoGeneratedCoverLetter || '';
    const hasSelection = !!currentSelection;
    const selectedTextCtx = currentSelection?.text || '';

    const userMessage: Message = {
      id: `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
      role: 'user',
      content: textToSend,
      timestamp: Date.now(),
      selection: currentSelection ? { text: selectedTextCtx } : undefined
    };

    const newMessages = [...messages, userMessage];
    setMessages(newMessages);
    setInput('');
    setIsLoading(true);
    setCurrentSelection(null);

    // Save/update this active chat in local history
    let activeChatId = chatId;
    let updatedHistory = [...chatHistory];

    if (!activeChatId) {
      activeChatId = Date.now().toString();
      setChatId(activeChatId);
      const newChat: ChatHistoryItem = {
        id: activeChatId,
        title: textToSend.substring(0, 30) + (textToSend.length > 30 ? '...' : ''),
        updatedAt: Date.now(),
        messages: newMessages
      };
      updatedHistory.unshift(newChat);
    } else {
      updatedHistory = updatedHistory.map(chat => 
        chat.id === activeChatId 
          ? { ...chat, updatedAt: Date.now(), messages: newMessages } 
          : chat
      );
    }
    saveToHistory(updatedHistory);

    try {
      let finalPrompt = '';
      if (hasSelection) {
        finalPrompt = `The user wants to improve a specific selection of their cover letter.
Original Selection:
"${selectedTextCtx}"

User Request:
${textToSend}

Please rewrite only the selected text to fulfill the request. Return the rewritten text directly.`;
      } else {
        finalPrompt = `The user wants to improve their cover letter body.
Full Cover Letter Body:
"${bodyContent}"

User Request:
${textToSend}

Please rewrite the cover letter body to fulfill the request. Return the rewritten body content directly. IMPORTANT: Ensure that the rewritten cover letter body ends with a formal sign-off (e.g., "Sincerely,\n\n${state.cvData?.basics?.name || 'Candidate'}") so the signature remains part of the body text.`;
      }

      const response = await fetch('/api/ai/improve-content', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          prompt: finalPrompt,
          cvData: state.cvData,
          jobData: state.jobData
        })
      });

      if (!response.ok) {
        throw new Error('AI service failed to respond.');
      }

      const result = await response.json();
      if (!result.success || !result.content) {
        throw new Error(result.error || 'Failed to generate improvement.');
      }

      const improvedText = result.content;

      // Apply the improvement directly to the canvas body
      let updatedBody = '';
      if (hasSelection) {
        if (bodyContent.includes(selectedTextCtx)) {
          updatedBody = bodyContent.replace(selectedTextCtx, improvedText);
        } else {
          const normalizedOriginal = selectedTextCtx.replace(/\s+/g, ' ');
          const index = bodyContent.replace(/\s+/g, ' ').indexOf(normalizedOriginal);
          if (index !== -1) {
            updatedBody = bodyContent.substring(0, index) + improvedText + bodyContent.substring(index + selectedTextCtx.length);
          } else {
            updatedBody = bodyContent + '\n\n' + improvedText;
          }
        }
      } else {
        updatedBody = improvedText;
      }

      if (onBodyChange) {
        onBodyChange(updatedBody);
      } else {
        dispatch({ type: 'SET_AUTO_COVER_LETTER', payload: { draft: updatedBody } });
      }

      const assistantMessage: Message = {
        id: `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
        role: 'assistant',
        content: hasSelection 
          ? "I've applied the rewritten text directly to your cover letter canvas!" 
          : "I've updated the cover letter body with the improvements directly on your canvas!",
        timestamp: Date.now()
      };

      const finalMessages = [...newMessages, assistantMessage];
      setMessages(finalMessages);

      // Save assistant response
      updatedHistory = updatedHistory.map(chat => 
        chat.id === activeChatId 
          ? { ...chat, updatedAt: Date.now(), messages: finalMessages } 
          : chat
      );
      saveToHistory(updatedHistory);
      
      toast.success('Changes applied directly to canvas!');

    } catch (error: any) {
      console.error('Mori cover letter chat error:', error);
      
      const errorMessage: Message = {
        id: `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
        role: 'assistant',
        content: "I'm sorry, I encountered a temporary connection issue. Please check your network or try again.",
        timestamp: Date.now(),
        isError: true
      };
      
      const finalMessages = [...newMessages, errorMessage];
      setMessages(finalMessages);

      updatedHistory = updatedHistory.map(chat => 
        chat.id === activeChatId 
          ? { ...chat, updatedAt: Date.now(), messages: finalMessages } 
          : chat
      );
      saveToHistory(updatedHistory);
    } finally {
      setIsLoading(false);
    }
  };

  const handleLoadChat = (id: string) => {
    const chat = chatHistory.find(c => c.id === id);
    if (chat) {
      setMessages(chat.messages);
      setChatId(id);
      setShowHistory(false);
    }
  };

  const handleDeleteChat = (e: React.MouseEvent, id: string) => {
    e.stopPropagation();
    if (!confirm('Are you sure you want to delete this chat?')) return;
    const updated = chatHistory.filter(c => c.id !== id);
    saveToHistory(updated);
    if (chatId === id) {
      handleNewChat();
    }
  };

  const handleRenameChat = (e: React.MouseEvent | React.KeyboardEvent, id: string) => {
    e.stopPropagation();
    if (e.type === 'keydown' && (e as React.KeyboardEvent).key !== 'Enter') return;
    
    if (!editTitle.trim()) {
      setEditingChatId(null);
      return;
    }

    const updated = chatHistory.map(c => c.id === id ? { ...c, title: editTitle } : c);
    saveToHistory(updated);
    setEditingChatId(null);
  };

  const handleNewChat = () => {
    setChatId(null);
    setMessages([
      {
        id: 'welcome',
        role: 'assistant',
        content: "Hi! I'm Mori. I can help you polish and write your cover letter. Highlight any paragraph or sentence on the left, then choose a quick action or tell me what to change.",
        timestamp: Date.now()
      }
    ]);
    setShowHistory(false);
  };

  return (
    <div className="flex flex-col h-full bg-white dark:bg-[#141810] border border-gray-200 dark:border-white/5 rounded-2xl shadow-sm relative overflow-hidden">
      
      {/* Header Bar */}
      <div className="px-4 py-2 border-b border-slate-200 dark:border-white/10 flex items-center justify-between bg-white dark:bg-transparent shrink-0">
        <div className="flex items-center gap-2 text-xs font-bold text-slate-700 dark:text-slate-300">
          <MessageSquare className="w-4 h-4 text-emerald-500" />
          {chatId ? chatHistory.find(c => c.id === chatId)?.title || 'Current Chat' : 'New Chat'}
        </div>
        <div className="flex items-center gap-1.5">
          <button 
            onClick={handleNewChat}
            className="p-1.5 hover:bg-slate-100 dark:hover:bg-white/5 rounded-md text-emerald-600 transition-all flex items-center gap-1 text-[10px] font-bold"
            title="New Chat"
          >
            <Plus className="w-3.5 h-3.5" /> New
          </button>
          <div className="w-px h-4 bg-slate-200 dark:bg-slate-700 mx-1"></div>
          <button 
            onClick={() => setShowHistory(!showHistory)}
            className={`p-1.5 rounded-md transition-all flex items-center gap-1 text-[10px] font-bold ${showHistory ? 'bg-slate-200 dark:bg-slate-800 text-slate-900 dark:text-white' : 'hover:bg-slate-100 dark:hover:bg-white/5 text-slate-600 dark:text-slate-400'}`}
            title="History"
          >
            <History className="w-3.5 h-3.5" /> History
          </button>
          {onClose && (
            <>
              <div className="w-px h-4 bg-slate-200 dark:bg-slate-700 mx-1"></div>
              <button 
                onClick={onClose}
                className="p-1.5 hover:bg-slate-100 dark:hover:bg-white/5 rounded-md text-gray-400 hover:text-red-500 transition-all"
                title="Close Mori Chat"
              >
                <X className="w-3.5 h-3.5" />
              </button>
            </>
          )}
        </div>
      </div>

      {/* Main Content Area */}
      <div className="flex-1 relative overflow-hidden">
        
        {/* History Overlay Panel */}
        <AnimatePresence>
          {showHistory && (
            <motion.div 
              initial={{ x: '100%' }}
              animate={{ x: 0 }}
              exit={{ x: '100%' }}
              transition={{ type: 'spring', damping: 25, stiffness: 200 }}
              className="absolute inset-0 z-20 bg-white dark:bg-[#141810] flex flex-col"
            >
              <div className="p-3 border-b border-slate-200 dark:border-white/10 bg-gray-50 dark:bg-transparent flex justify-between items-center">
                <span className="text-xs font-bold text-slate-600 dark:text-slate-400">Previous Conversations</span>
                <button onClick={() => setShowHistory(false)} className="text-slate-400 hover:text-slate-600 dark:hover:text-white"><X className="w-4 h-4" /></button>
              </div>
              <div className="flex-1 overflow-y-auto p-2 space-y-1 custom-scrollbar">
                {chatHistory.length === 0 ? (
                  <div className="text-center p-6 text-xs text-slate-400 italic">No previous chats found.</div>
                ) : (
                  chatHistory.map((chat) => (
                    <div 
                      key={chat.id}
                      onClick={() => handleLoadChat(chat.id)}
                      className={`group flex items-center justify-between p-3 rounded-lg cursor-pointer transition-colors border ${chatId === chat.id ? 'bg-emerald-50 dark:bg-emerald-500/10 border-emerald-200 dark:border-emerald-500/20' : 'bg-transparent border-transparent hover:bg-slate-50 dark:hover:bg-white/5 hover:border-slate-200 dark:hover:border-white/10'}`}
                    >
                      {editingChatId === chat.id ? (
                        <div className="flex items-center gap-2 flex-1" onClick={e => e.stopPropagation()}>
                          <input 
                            autoFocus
                            value={editTitle}
                            onChange={e => setEditTitle(e.target.value)}
                            onKeyDown={e => handleRenameChat(e, chat.id)}
                            className="flex-1 text-xs px-2 py-1 bg-white dark:bg-[#141810] border border-emerald-500 outline-none rounded"
                          />
                          <button onClick={(e) => handleRenameChat(e, chat.id)} className="text-emerald-600 hover:text-emerald-700">Save</button>
                        </div>
                      ) : (
                        <>
                          <div className="flex-1 min-w-0 pr-3">
                            <h4 className={`text-xs font-semibold truncate ${chatId === chat.id ? 'text-emerald-700 dark:text-emerald-400' : 'text-slate-700 dark:text-slate-300'}`}>
                              {chat.title}
                            </h4>
                            <p className="text-[10px] text-slate-400 mt-0.5">
                              {new Date(chat.updatedAt).toLocaleDateString()}
                            </p>
                          </div>
                          <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                            <button 
                              onClick={(e) => { e.stopPropagation(); setEditTitle(chat.title); setEditingChatId(chat.id); }}
                              className="p-1.5 text-slate-400 hover:text-blue-500 hover:bg-blue-50 dark:hover:bg-blue-500/10 rounded"
                            >
                              <Edit2 className="w-3.5 h-3.5" />
                            </button>
                            <button 
                              onClick={(e) => handleDeleteChat(e, chat.id)}
                              className="p-1.5 text-slate-400 hover:text-red-500 hover:bg-red-50 dark:hover:bg-red-500/10 rounded"
                            >
                              <Trash2 className="w-3.5 h-3.5" />
                            </button>
                          </div>
                        </>
                      )}
                    </div>
                  ))
                )}
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Messages Area */}
        <div 
          ref={scrollRef}
          className="absolute inset-0 overflow-y-auto p-4 space-y-4 hide-scrollbar pb-32"
        >
          {messages.map((m, idx) => (
            <div key={m.id} className="group">
              <MoriMessageBubble
                message={m}
                onOptionClick={(prompt) => handleSend(prompt)}
                isLatest={idx === messages.length - 1 && m.role === 'assistant'}
                disabled={isLoading}
              />
              {(m.role === 'assistant') && (idx === messages.length - 1 || m.id === 'welcome') && (
                <MoriSuggestionChips
                  suggestions={SUGGESTIONS}
                  onSelect={(prompt) => handleSend(prompt)}
                  disabled={isLoading}
                />
              )}
            </div>
          ))}
          {isLoading && <MoriLoadingIndicator />}
        </div>
      </div>

      {/* Input Area (sticks to bottom) */}
      <div className="absolute bottom-0 left-0 right-0 p-3 pt-0 bg-gradient-to-t from-white via-white to-transparent dark:from-[#141810] dark:via-[#141810] z-10 pointer-events-none">
        
        {/* Selection Banner */}
        <AnimatePresence>
          {currentSelection && (
            <motion.div 
              initial={{ y: 20, opacity: 0 }}
              animate={{ y: 0, opacity: 1 }}
              exit={{ y: 10, opacity: 0, scale: 0.95 }}
              className="pointer-events-auto bg-emerald-50 dark:bg-emerald-500/10 border border-emerald-200 dark:border-emerald-500/30 rounded-t-xl px-3 py-2 flex items-center justify-between mb-0 shadow-sm mx-1"
            >
              <div className="flex items-center gap-2 overflow-hidden flex-1 mr-2">
                <MousePointer2 className="w-3.5 h-3.5 text-emerald-600 dark:text-emerald-400 shrink-0" />
                <div className="text-[11px] font-medium text-emerald-800 dark:text-emerald-300 truncate">
                  <span className="opacity-70 mr-1">Targeting Selection:</span>
                  "{currentSelection.text}"
                </div>
              </div>
              <button 
                onClick={() => setCurrentSelection(null)}
                className="p-1 hover:bg-emerald-200 dark:hover:bg-emerald-500/30 rounded-md text-emerald-600 dark:text-emerald-400 transition-colors shrink-0"
              >
                <X className="w-3.5 h-3.5" />
              </button>
            </motion.div>
          )}
        </AnimatePresence>

        <div className={`pointer-events-auto relative group shadow-xl shadow-slate-200/50 dark:shadow-none bg-white dark:bg-[#141810] border border-slate-200 dark:border-white/10 transition-all ${currentSelection ? 'rounded-b-xl rounded-t-none border-t-0' : 'rounded-2xl'}`}>
          <textarea
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === 'Enter' && !e.shiftKey) {
                e.preventDefault();
                handleSend();
              }
            }}
            placeholder={currentSelection ? "Instruct Mori to update selection..." : "Ask Mori to polish your cover letter..."}
            rows={1}
            className="w-full bg-transparent px-4 py-3.5 pr-12 text-sm focus:outline-none resize-none dark:text-white dark:placeholder-slate-500"
            style={{ minHeight: '48px', maxHeight: '120px' }}
          />
          <button
            onClick={() => handleSend()}
            disabled={!input.trim() || isLoading}
            className={`absolute right-2 top-1/2 -translate-y-1/2 p-2 rounded-xl transition-all ${
              input.trim() && !isLoading 
                ? 'bg-emerald-500 hover:bg-emerald-600 text-white shadow-md shadow-emerald-500/20 scale-100' 
                : 'bg-slate-100 dark:bg-white/5 text-slate-400 dark:text-slate-500 scale-95'
            }`}
          >
            <Send className="w-4 h-4" />
          </button>
        </div>
      </div>
    </div>
  );
};

export default MoriCoverLetterChat;
