'use client';

import React, { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  Sparkles, FileText, ChevronRight, Loader2, ArrowRight, AlertTriangle, 
  PenTool, WifiOff, Layout, Type, Search, Target, HelpCircle, CheckCircle, 
  Save, X, Palette, LayoutTemplate, Download, Settings, ChevronDown, Check,
  Baseline, AlignLeft, MoveHorizontal, Zap, MousePointer2, Brain, History,
  RefreshCcw, Eye, Clipboard, Mail, FileJson, Clock, Flame, ShieldCheck,
  TrendingUp, UserCheck
} from 'lucide-react';
import { useResumeEnhancer } from '@/contexts/ResumeEnhancerContext';
import CoverLetterLayoutEngine, { CoverLetterDesignProps } from '../../cover-letter-engine/CoverLetterLayoutEngine';
import { 
  ClassicHeader, 
  ModernHeader, 
  MinimalHeader,
  TypographicHeader,
  ColumnSplitHeader,
  AccentBannerHeader 
} from '../../cover-letter-engine/snippets/headers/HeaderSnippets';
import { useUnifiedAuth } from '@/lib/hooks/useUnifiedAuth';
import guestCVService from '@/lib/services/guestCVService';
import { checkSyntaxAndGrammar } from '@/lib/utils/offline-grammar-check';
import { Button } from '@/components/ui/button';
import toast from 'react-hot-toast';
import LetterGuidePanel from '@/components/resume-enhancer/panels/LetterGuidePanel';
import MoriCoverLetterChat from '@/components/resume-enhancer/panels/MoriCoverLetterChat';

interface Step4CoverLetterProps {
  onComplete: () => void;
}

const TEMPLATES = [
  { id: 'modern', name: 'Modern', icon: Sparkles, desc: 'Professional, lime accents' },
  { id: 'classic', name: 'Classic', icon: Type, desc: 'Traditional serif style' },
  { id: 'minimal', name: 'Minimal', icon: Layout, desc: 'Clean and simple' },
  { id: 'typographic', name: 'Typographic', icon: Baseline, desc: 'Bold display' },
  { id: 'column-split', name: 'Column Split', icon: MoveHorizontal, desc: 'Side-by-side header' },
  { id: 'accent-banner', name: 'Accent Banner', icon: LayoutTemplate, desc: 'High-impact banner' }
] as const;

export default function Step4CoverLetter({ onComplete }: Step4CoverLetterProps) {
  const { state, dispatch, setJobSidebarOpen } = useResumeEnhancer();
  const { isAuthenticated } = useUnifiedAuth();
  const [isGenerating, setIsGenerating] = useState(false);
  const [isEditing, setIsEditing] = useState(true);
  const [templateType, setTemplateType] = useState<any>('modern');

  // AI Configuration State
  const [aiMode, setAiMode] = useState<'manual' | 'assist' | 'full'>('assist');
  const [aiTone, setAiTone] = useState('Professional');
  const [aiLength, setAiLength] = useState(50); // 0-100 scale
  const [aiCreativity, setAiCreativity] = useState(30); // 0-100 scale
  const [aiPersonalization, setAiPersonalization] = useState(70); // 0-100 scale
  
  const [skipExperience, setSkipExperience] = useState(false);
  const [skipProjects, setSkipProjects] = useState(false);

  // UI State
  const [zoom, setZoom] = useState(100);
  const [pageFormat, setPageFormat] = useState<'a4' | 'letter'>('a4');
  const [activeLeftSidebar, setActiveLeftSidebar] = useState<string | null>(null);
  const [grammarIssues, setGrammarIssues] = useState<any[]>([]);
  const [matchScore, setMatchScore] = useState(82);
  const [showMoriChat, setShowMoriChat] = useState(false);
  const [showTemplateSelector, setShowTemplateSelector] = useState(false);

  // Design State
  const [design, setDesign] = useState<CoverLetterDesignProps>({
    fontSize: 15,
    lineHeight: 1.6,
    pageMargin: 6,
    accentColor: '#80FF00',
    fontFamily: 'font-sans'
  });

  const hasJD = !!(state.jobData?.description || state.jobData?.jobDescription);
  const [isOffline, setIsOffline] = useState(false);

  // Auto-select template based on CV template ID
  useEffect(() => {
    const templateId = state.selectedTemplate?.id || (state.selectedTemplate as any)?._id;
    if (templateId) {
      const lowerId = templateId.toLowerCase();
      if (lowerId.includes('classic') || lowerId.includes('traditional') || lowerId.includes('harvard')) {
        setTemplateType('classic');
        setDesign(prev => ({ ...prev, fontFamily: 'font-serif' }));
      } else if (lowerId.includes('minimal') || lowerId.includes('simple')) {
        setTemplateType('minimal');
        setDesign(prev => ({ ...prev, fontFamily: 'font-sans' }));
      } else {
        setTemplateType('modern');
        setDesign(prev => ({ ...prev, fontFamily: 'font-sans' }));
      }
    }
  }, [state.selectedTemplate]);

  useEffect(() => {
    if (state.autoGeneratedCoverLetter) {
      const issues = checkSyntaxAndGrammar({ basics: { summary: state.autoGeneratedCoverLetter } });
      setGrammarIssues(issues);
    } else {
      setGrammarIssues([]);
    }
  }, [state.autoGeneratedCoverLetter]);

  useEffect(() => {
    if (typeof navigator !== 'undefined') {
      setIsOffline(!navigator.onLine);
    }
    const handleOnline = () => setIsOffline(false);
    const handleOffline = () => setIsOffline(true);
    window.addEventListener('online', handleOnline);
    window.addEventListener('offline', handleOffline);
    return () => {
      window.removeEventListener('online', handleOnline);
      window.removeEventListener('offline', handleOffline);
    };
  }, []);

  const handleGenerate = async () => {
    if (!state.cvData || !state.jobData) {
      toast.error('CV and Job Description are required for AI generation.');
      return;
    }

    setIsGenerating(true);
    const loadingToast = toast.loading('AI is crafting your tailored letter...');
    
    try {
      const response = await fetch('/api/ai/cover-letter-generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          cvData: state.cvData,
          jobData: state.jobData,
          recipientName: state.jobData?.contactPerson || 'Hiring Manager',
          companyName: state.jobData?.company || 'the company',
          tone: aiTone,
          length: aiLength,
          creativity: aiCreativity,
          personalization: aiPersonalization,
          skipExperience,
          skipProjects,
          mode: aiMode
        })
      });
      
      const data = await response.json();
      
      if (response.ok && data.success) {
        const generatedText = data.body || data.content;
        dispatch({ 
          type: 'SET_AUTO_COVER_LETTER', 
          payload: { draft: generatedText } 
        });
        toast.success('Success! Your letter has been tailored.', { id: loadingToast });
        
        // Update match quality if returned
        if (data.structuredContent?.metadata?.match_quality) {
            setMatchScore(data.structuredContent.metadata.match_quality);
        }
      } else {
        throw new Error(data.error || 'Failed to generate');
      }
    } catch (error) {
      console.error('Failed to generate cover letter:', error);
      toast.error('AI Assistant is currently unavailable. Please try again.', { id: loadingToast });
    } finally {
      setIsGenerating(false);
    }
  };

  const handleBodyChange = (newContent: string) => {
    dispatch({ 
      type: 'SET_AUTO_COVER_LETTER', 
      payload: { draft: newContent } 
    });
  };

  const today = new Date().toLocaleDateString('en-GB', { day: '2-digit', month: '2-digit', year: 'numeric' });
  const name = state.cvData?.basics?.name || 'Your Name';
  const email = state.cvData?.basics?.email || 'email@example.com';
  const phone = state.cvData?.basics?.phone || '';
  const location = state.cvData?.basics?.location?.city ? `${state.cvData.basics.location.city}${state.cvData.basics.location.countryCode ? `, ${state.cvData.basics.location.countryCode}` : ''}` : '';
  const recipientName = state.jobData?.contactPerson || 'Hiring Manager';
  const companyName = state.jobData?.company || 'Company Name';

  return (
    <div className="flex flex-col h-[calc(100vh-64px)] min-h-0 relative overflow-hidden bg-gray-50 dark:bg-[var(--bg-primary)]">
      <div className="flex-1 h-full flex overflow-hidden relative px-3 pb-3 pt-3 gap-3">
        
        {/* Canvas Wrapper */}
        <div className="flex-1 min-h-0 relative flex flex-col rounded-xl overflow-hidden shadow-sm shadow-black/10 dark:shadow-black/30 border border-gray-200 dark:border-white/5 text-gray-900">
          <div className="flex-1 min-h-0 overflow-y-auto bg-gray-100/50 dark:bg-[#141810] p-4 lg:p-8 flex justify-center custom-scrollbar">
            <div className="transition-transform duration-300 transform origin-top pb-20" style={{ transform: `scale(${zoom / 100})` }}>
              <CoverLetterLayoutEngine 
                templateType={templateType}
                onTemplateTypeChange={setTemplateType}
                pageFormat={pageFormat}
                headerProps={{
                  name,
                  email,
                  phone,
                  location,
                  date: today,
                  recipientName,
                  companyName
                }}
                bodyContent={state.autoGeneratedCoverLetter || ''}
                isEditing={isEditing}
                onBodyChange={handleBodyChange}
                design={design}
                showMoriChat={showMoriChat}
                onToggleMoriChat={() => setShowMoriChat(!showMoriChat)}
                onChangeHeaderStyle={() => setShowTemplateSelector(true)}
              />
            </div>
          </div>

          {/* Floating Zoom & Page Controls */}
          <div className="absolute bottom-6 left-1/2 -translate-x-1/2 z-[40] flex items-center gap-2 pointer-events-none">
            <div className="px-3 py-1.5 rounded-xl border shadow-xl backdrop-blur-md flex items-center gap-3 text-[10px] font-bold uppercase tracking-wider bg-white/90 dark:bg-[#111]/90 text-gray-900 dark:text-gray-100 border-gray-200 dark:border-[#2a2a2a] opacity-90 hover:opacity-100 transition-opacity pointer-events-auto">
              <button 
                onClick={() => setPageFormat(pageFormat === 'a4' ? 'letter' : 'a4')}
                className="flex items-center gap-1.5 px-1.5 py-0.5 rounded-md transition-all hover:bg-emerald-500/10 text-emerald-600 dark:text-[#7EE787]"
              >
                <Layout size={10} />
                {pageFormat === 'a4' ? 'A4' : 'Letter'}
              </button>
            </div>

            <div className="px-2 py-1.5 rounded-xl border shadow-xl backdrop-blur-md flex items-center gap-2 bg-white/90 dark:bg-[#111]/90 text-gray-900 dark:text-gray-100 border-gray-200 dark:border-[#2a2a2a] opacity-90 hover:opacity-100 transition-opacity pointer-events-auto">
              <div className="flex items-center gap-0.5">
                <button 
                  onClick={() => setZoom(Math.max(50, zoom - 10))}
                  className={`p-1.5 rounded-lg hover:bg-emerald-500/20 transition-all ${zoom <= 50 ? 'opacity-30 cursor-not-allowed' : 'text-gray-500 dark:text-gray-400'}`}
                >
                  <Search size={14} className="rotate-90" />
                </button>
                <input 
                  type="range" min="50" max="200" step="5" value={zoom} 
                  onChange={(e) => setZoom(parseInt(e.target.value))}
                  className="w-20 accent-[#80FF00] h-1 bg-gray-200 dark:bg-gray-700 rounded-lg appearance-none cursor-pointer"
                />
                <button 
                  onClick={() => setZoom(Math.min(200, zoom + 10))}
                  className={`p-1.5 rounded-lg hover:bg-emerald-500/20 transition-all ${zoom >= 200 ? 'opacity-30 cursor-not-allowed' : 'text-gray-500 dark:text-gray-400'}`}
                >
                  <Search size={14} />
                </button>
              </div>
              
              <button 
                onClick={() => setZoom(100)}
                className={`min-w-[42px] px-1.5 py-1 text-[9px] font-black rounded-md transition-all border ${zoom === 100 ? 'bg-[#80FF00]/20 border-[#80FF00]/50 text-[#80FF00]' : 'bg-transparent border-gray-500/20 hover:border-[#80FF00]/50 text-gray-500 dark:text-gray-400'}`}
              >
                {zoom}%
              </button>
            </div>
          </div>
        </div>

        {/* MIDDLE COLUMN - LETTER GUIDE (radial progress, metrics, context) */}
        <div className="flex flex-col w-[320px] shrink-0 h-full relative z-10">
          <LetterGuidePanel 
            matchScore={matchScore}
            templateType={templateType}
            setTemplateType={setTemplateType}
            design={design}
            setDesign={setDesign}
            isEditing={isEditing}
            setIsEditing={setIsEditing}
            onComplete={onComplete}
            onUpdateTarget={() => setJobSidebarOpen(true)}
            showMoriChat={showMoriChat}
            onToggleMoriChat={() => setShowMoriChat(!showMoriChat)}
          />
        </div>

        {/* RIGHT COLUMN - MORI AI ASSISTANT CHAT */}
        <AnimatePresence>
          {showMoriChat && (
            <motion.div 
              initial={{ opacity: 0, x: 20, width: 0 }}
              animate={{ opacity: 1, x: 0, width: 360 }}
              exit={{ opacity: 0, x: 20, width: 0 }}
              transition={{ type: 'spring', damping: 25, stiffness: 200 }}
              className="hidden lg:flex flex-col shrink-0 h-full relative z-10 min-h-0 overflow-hidden"
            >
              <MoriCoverLetterChat 
                onBodyChange={handleBodyChange} 
                onClose={() => setShowMoriChat(false)}
              />
            </motion.div>
          )}
        </AnimatePresence>
      </div>

      {showTemplateSelector && (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-[100] no-print">
          <div className="bg-white dark:bg-[#141810] border border-slate-200 dark:border-white/10 rounded-2xl shadow-2xl w-[95vw] md:w-[90vw] max-w-5xl max-h-[85vh] flex flex-col overflow-hidden animate-fade-in-up animate-in duration-200">
            {/* Modal Header */}
            <div className="px-6 py-4 border-b border-slate-100 dark:border-white/5 flex items-center justify-between bg-slate-50 dark:bg-transparent">
              <div>
                <h3 className="font-extrabold text-sm uppercase tracking-wider text-slate-800 dark:text-white flex items-center gap-2">
                  <LayoutTemplate className="w-4 h-4 text-emerald-500" />
                  Choose Header Style
                </h3>
                <p className="text-[10px] text-slate-400 uppercase tracking-widest mt-0.5">Select a layout template for your cover letter header</p>
              </div>
              <button 
                type="button"
                onClick={() => setShowTemplateSelector(false)} 
                className="p-1.5 rounded-lg text-slate-400 hover:text-slate-600 dark:hover:text-white hover:bg-slate-100 dark:hover:bg-white/5 transition-all"
              >
                <X className="w-5 h-5" />
              </button>
            </div>
            
            {/* Modal Grid Content */}
            <div className="flex-1 overflow-y-auto p-6 custom-scrollbar">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {TEMPLATES.map((t) => {
                  const isSelected = templateType === t.id;
                  const PreviewHeaderComponent = (() => {
                    switch (t.id) {
                      case 'classic': return ClassicHeader;
                      case 'minimal': return MinimalHeader;
                      case 'typographic': return TypographicHeader;
                      case 'column-split': return ColumnSplitHeader;
                      case 'accent-banner': return AccentBannerHeader;
                      case 'modern':
                      default: return ModernHeader;
                    }
                  })();
                  
                  return (
                    <button
                      key={t.id}
                      type="button"
                      onClick={() => {
                        setTemplateType(t.id);
                        setShowTemplateSelector(false);
                      }}
                      className={`group flex flex-col rounded-xl border-2 text-left overflow-hidden transition-all ${
                        isSelected 
                          ? 'border-emerald-500 bg-emerald-500/[0.02]' 
                          : 'border-slate-200 dark:border-white/5 hover:border-emerald-400 bg-transparent'
                      }`}
                    >
                      {/* Live Scaled Down Preview */}
                      <div className="w-full h-[140px] bg-white border-b border-slate-150 dark:border-white/5 flex justify-center items-start p-3 relative overflow-hidden select-none [container-type:inline-size]">
                        <div 
                          className="w-[800px] shrink-0 origin-top transform" 
                          style={{ 
                            width: '800px',
                            transform: 'scale(min(0.55, calc((100cqw - 24px) / 800)))'
                          }}
                        >
                          <PreviewHeaderComponent {...{
                            name,
                            email,
                            phone,
                            location,
                            date: today,
                            recipientName,
                            companyName
                          }} />
                        </div>
                        {isSelected && (
                          <div className="absolute top-2 right-2 bg-emerald-500 text-white rounded-full p-1 shadow">
                            <Check className="w-3.5 h-3.5 stroke-[3]" />
                          </div>
                        )}
                      </div>
                      
                      {/* Metadata */}
                      <div className="p-3 bg-slate-50/50 dark:bg-white/[0.01] flex-1 flex flex-col justify-center">
                        <div className="font-extrabold text-xs text-slate-800 dark:text-slate-200 group-hover:text-emerald-600 transition-colors uppercase tracking-tight">
                          {t.name}
                        </div>
                        <div className="text-[10px] text-slate-400 font-medium mt-0.5">
                          {t.desc}
                        </div>
                      </div>
                    </button>
                  );
                })}
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
