import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Sparkles, FileText, ChevronRight, Loader2, ArrowRight, AlertTriangle, PenTool, WifiOff, Layout, Type } from 'lucide-react';
import { useResumeEnhancer } from '@/contexts/ResumeEnhancerContext';
import CoverLetterLayoutEngine from '../../cover-letter-engine/CoverLetterLayoutEngine';
import { useUnifiedAuth } from '@/lib/hooks/useUnifiedAuth';
import guestCVService from '@/lib/services/guestCVService';

interface Step4CoverLetterProps {
  onComplete: () => void;
}

export default function Step4CoverLetter({ onComplete }: Step4CoverLetterProps) {
  const { state, dispatch } = useResumeEnhancer();
  const { isAuthenticated } = useUnifiedAuth();
  const [isGenerating, setIsGenerating] = useState(false);
  const [isEditing, setIsEditing] = useState(false);
  const [templateType, setTemplateType] = useState<'classic' | 'modern' | 'minimal'>('modern');

  const hasJD = !!(state.jobData?.description || state.jobData?.jobDescription);
  const [isOffline, setIsOffline] = useState(false);
  const [isSyncing, setIsSyncing] = useState(false);

  useEffect(() => {
    if (typeof navigator !== 'undefined') {
      setIsOffline(!navigator.onLine);
    }

    const syncDraft = async () => {
      if (!isAuthenticated) {
        setIsSyncing(true);
        try {
          await guestCVService.saveGuestDraft({
            cvData: state.cvData,
            currentStep: 4,
            completedSteps: [1, 2, 3],
            targetRole: state.targetRole,
            seniorityLevel: state.seniorityLevel,
            templateId: state.selectedTemplate?.id || (state.selectedTemplate as any)?._id,
            template: state.selectedTemplate,
            cvTitle: state.cvTitle,
            jobData: state.jobData,
            autoGeneratedCoverLetter: state.autoGeneratedCoverLetter
          });
        } catch (err) {
          console.error('Failed to sync draft on reconnect:', err);
        } finally {
          setIsSyncing(false);
        }
      }
    };

    const handleOnline = () => {
      setIsOffline(false);
      syncDraft();
    };
    const handleOffline = () => setIsOffline(true);

    window.addEventListener('online', handleOnline);
    window.addEventListener('offline', handleOffline);

    return () => {
      window.removeEventListener('online', handleOnline);
      window.removeEventListener('offline', handleOffline);
    };
  }, [isAuthenticated, state]);

  const handleGenerate = async () => {
    setIsGenerating(true);
    try {
      const response = await fetch('/api/ai/cover-letter-generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          cvData: state.cvData,
          jobData: state.jobData,
          recipientName: 'Hiring Manager',
          companyName: state.jobData?.company || 'Company'
        })
      });
      
      let generatedText = '';
      if (response.ok) {
        const data = await response.json();
        generatedText = data.content || data.body || '';
      }
      
      if (!generatedText) {
        generatedText = `I am writing to express my interest in the position at your company. With my background in ${state.targetRole || 'this field'}, I am confident in my ability to contribute effectively to your team.\n\nThroughout my career, I have developed skills that align well with your requirements. I would welcome the opportunity to discuss how my experience and enthusiasm would be a great fit for this role.`;
      }

      dispatch({ 
        type: 'SET_AUTO_COVER_LETTER', 
        payload: { draft: generatedText } 
      });
    } catch (error) {
      console.error('Failed to generate cover letter:', error);
      dispatch({ 
        type: 'SET_AUTO_COVER_LETTER', 
        payload: { draft: "I am writing to express my interest in the position. My skills align well with the requirements." } 
      });
    } finally {
      setIsGenerating(false);
    }
  };

  const handleBodyChange = (newContent: string) => {
    dispatch({ 
      type: 'SET_AUTO_COVER_LETTER', 
      payload: { draft: newContent } 
    });
  };

  const today = new Date().toLocaleDateString();
  const name = state.cvData?.basics?.name || 'Your Name';
  const email = state.cvData?.basics?.email || 'email@example.com';
  const phone = state.cvData?.basics?.phone || '';
  const location = state.cvData?.basics?.location?.city ? `${state.cvData.basics.location.city}${state.cvData.basics.location.countryCode ? `, ${state.cvData.basics.location.countryCode}` : ''}` : '';
  const recipientName = state.jobData?.contactPerson || 'Hiring Manager';
  const companyName = state.jobData?.company || 'Company Name';

  return (
    <motion.div 
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="flex-1 min-h-0 flex gap-4 w-full max-w-[1600px] mx-auto px-4 lg:px-6 py-4 lg:py-6 relative bg-gray-50 dark:bg-[var(--bg-primary)]"
    >
      {/* Main Content Area (Left side - Canvas) */}
      <div className="flex-1 min-h-0 relative flex flex-col rounded-xl overflow-hidden shadow-sm shadow-black/10 dark:shadow-black/30">
        <div className="flex-1 min-h-0 overflow-y-auto bg-gray-100/50 dark:bg-[#141810] p-4 lg:p-8">
          <div className="w-full max-w-4xl mx-auto">
            <CoverLetterLayoutEngine 
              templateType={templateType}
              headerProps={{
                name,
                email,
                phone,
                location,
                date: today,
                recipientName,
                companyName
              }}
              bodyContent={state.autoGeneratedCoverLetter || ''}
              isEditing={isEditing}
              onBodyChange={handleBodyChange}
            />
          </div>
        </div>
      </div>
      
      {/* Right Panel (AI Tools & Controls) */}
      <div className="hidden lg:flex flex-col w-80 shrink-0 h-full relative z-10 gap-4 overflow-y-auto">
        <div className="bg-white dark:bg-[#1a230f] rounded-xl shadow-sm border border-gray-100 dark:border-white/5 p-6 flex flex-col gap-6">
          
          <div>
            <div className="w-12 h-12 bg-lime-500/10 rounded-full flex items-center justify-center mb-4 border border-lime-500/20">
              <FileText className="w-6 h-6 text-lime-500" />
            </div>
            <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-2">
              Cover Letter
            </h3>
            <p className="text-sm text-gray-500 dark:text-gray-400">
              Generate a perfectly tailored cover letter to boost your chances.
            </p>
          </div>

          {isOffline && (
            <div className="p-3 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-700/50 rounded-lg text-red-800 dark:text-red-200 flex items-start text-xs">
              <WifiOff className="w-4 h-4 mr-2 flex-shrink-0" />
              <p>Offline. Progress is saved locally.</p>
            </div>
          )}

          {!hasJD && !isOffline && (
            <div className="p-3 bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-700/50 rounded-lg text-amber-800 dark:text-amber-200 flex items-start text-xs">
              <AlertTriangle className="w-4 h-4 mr-2 flex-shrink-0" />
              <p>No Job Description provided. Results may be generic.</p>
            </div>
          )}

          <div className="flex flex-col gap-3">
            <button 
              className="w-full group relative px-4 py-3 bg-lime-500 hover:bg-lime-400 text-black font-bold rounded-xl transition-all shadow-[0_0_15px_rgba(132,204,22,0.2)] hover:shadow-[0_0_20px_rgba(132,204,22,0.4)] overflow-hidden flex items-center justify-center gap-2 disabled:opacity-70 disabled:cursor-not-allowed"
              onClick={handleGenerate}
              disabled={isGenerating || isOffline}
            >
              {isGenerating ? (
                <Loader2 className="w-4 h-4 animate-spin" />
              ) : (
                <Sparkles className="w-4 h-4" />
              )}
              <span>{isGenerating ? 'Generating...' : (state.autoGeneratedCoverLetter ? 'Regenerate AI' : 'Generate AI Letter')}</span>
            </button>

            <button 
              className={`w-full px-4 py-3 font-bold rounded-xl transition-all flex items-center justify-center gap-2 ${
                isEditing 
                  ? 'bg-lime-100 text-lime-800 dark:bg-lime-900/30 dark:text-lime-400' 
                  : 'bg-gray-100 dark:bg-white/5 hover:bg-gray-200 dark:hover:bg-white/10 text-gray-700 dark:text-gray-300'
              }`}
              onClick={() => setIsEditing(!isEditing)}
              disabled={isGenerating}
            >
              {isEditing ? <Layout className="w-4 h-4" /> : <PenTool className="w-4 h-4" />}
              {isEditing ? 'Preview Letter' : 'Manual Edit'}
            </button>
          </div>

          <div className="pt-4 border-t border-gray-100 dark:border-white/10">
            <h4 className="text-sm font-semibold text-gray-900 dark:text-white mb-3 flex items-center gap-2">
              <Type className="w-4 h-4 text-gray-500" />
              Template Style
            </h4>
            <div className="grid grid-cols-3 gap-2">
              {(['classic', 'modern', 'minimal'] as const).map(type => (
                <button
                  key={type}
                  onClick={() => setTemplateType(type)}
                  className={`py-2 text-xs font-medium rounded-lg capitalize transition-colors ${
                    templateType === type 
                      ? 'bg-gray-900 text-white dark:bg-white dark:text-black' 
                      : 'bg-gray-100 text-gray-600 hover:bg-gray-200 dark:bg-white/5 dark:text-gray-400 dark:hover:bg-white/10'
                  }`}
                >
                  {type}
                </button>
              ))}
            </div>
          </div>
        </div>

        <div className="mt-auto">
          <button
            onClick={onComplete}
            className="w-full px-6 py-4 bg-gray-900 hover:bg-gray-800 dark:bg-white dark:hover:bg-gray-200 text-white dark:text-black font-bold rounded-xl transition-all flex items-center justify-center gap-2 shadow-lg"
          >
            Continue to Review
            <ArrowRight className="w-4 h-4" />
          </button>
        </div>
      </div>
    </motion.div>
  );
}