'use client';

import React, { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  Sparkles, FileText, ChevronRight, Loader2, ArrowRight, AlertTriangle, 
  PenTool, WifiOff, Layout, Type, Search, Target, HelpCircle, CheckCircle, 
  Save, X, Palette, LayoutTemplate, Download, Settings, ChevronDown, Check,
  Baseline, AlignLeft, MoveHorizontal, Zap, MousePointer2, Brain, History,
  RefreshCcw, Eye, Clipboard, Mail, FileJson, Clock, Flame, ShieldCheck,
  TrendingUp, UserCheck, ZoomIn, ZoomOut
} from 'lucide-react';
import { useResumeEnhancer } from '@/contexts/ResumeEnhancerContext';
import CoverLetterLayoutEngine, { CoverLetterDesignProps } from '../../cover-letter-engine/CoverLetterLayoutEngine';
import { 
  ClassicHeader, 
  ModernHeader, 
  MinimalHeader,
  TypographicHeader,
  ColumnSplitHeader,
  AccentBannerHeader,
  CreativeEdgeHeader,
  ExecutiveSlateHeader
} from '../../cover-letter-engine/snippets/headers/HeaderSnippets';
import { useUnifiedAuth } from '@/lib/hooks/useUnifiedAuth';
import guestCVService from '@/lib/services/guestCVService';
import { checkSyntaxAndGrammar } from '@/lib/utils/offline-grammar-check';
import { Button } from '@/components/ui/button';
import toast from 'react-hot-toast';
import LetterGuidePanel from '@/components/resume-enhancer/panels/LetterGuidePanel';
import MoriCoverLetterChat from '@/components/resume-enhancer/panels/MoriCoverLetterChat';
import EditorOnboarding from '@/components/resume-enhancer/components/EditorOnboarding';

function normalizeCoverLetterMetadata(metadata: any): {
  templateType: string;
  design: any;
  matchQuality?: number;
  primaryKeywords?: string[];
  tone?: string;
  structuredBody?: any;
} {
  if (!metadata || typeof metadata !== 'object') {
    return {
      templateType: 'modern',
      design: {
        fontSize: 15,
        lineHeight: 1.6,
        pageMargin: 6,
        accentColor: '#80FF00',
        fontFamily: 'font-sans'
      }
    };
  }

  const normalizedDesign = metadata.design && typeof metadata.design === 'object'
    ? metadata.design
    : {
        fontSize: metadata.fontSize || 15,
        lineHeight: metadata.lineHeight || 1.6,
        pageMargin: metadata.pageMargin || 6,
        accentColor: metadata.accentColor || '#80FF00',
        fontFamily: metadata.fontFamily || 'font-sans'
      };

  return {
    templateType: metadata.templateType || 'modern',
    design: normalizedDesign,
    matchQuality: typeof metadata.match_quality === 'number' ? metadata.match_quality : undefined,
    primaryKeywords: Array.isArray(metadata.primary_keywords) ? metadata.primary_keywords : undefined,
    tone: typeof metadata.tone === 'string' ? metadata.tone : undefined,
    structuredBody: metadata.structuredBody || metadata.sections || undefined
  };
}

interface Step4CoverLetterProps {
  onComplete: () => void;
}

const TEMPLATES = [
  { id: 'modern', name: 'Modern', icon: Sparkles, desc: 'Professional, lime accents' },
  { id: 'classic', name: 'Classic', icon: Type, desc: 'Traditional serif style' },
  { id: 'minimal', name: 'Minimal', icon: Layout, desc: 'Clean and simple' },
  { id: 'typographic', name: 'Typographic', icon: Baseline, desc: 'Bold display' },
  { id: 'column-split', name: 'Column Split', icon: MoveHorizontal, desc: 'Side-by-side header' },
  { id: 'accent-banner', name: 'Accent Banner', icon: LayoutTemplate, desc: 'High-impact banner' },
  { id: 'creative-edge', name: 'Creative Edge', icon: Sparkles, desc: 'Chic accent style' },
  { id: 'executive-slate', name: 'Executive Slate', icon: ShieldCheck, desc: 'Sleek executive layout' }
] as const;

export default function Step4CoverLetter({ onComplete }: Step4CoverLetterProps) {
  const { state, dispatch, setJobSidebarOpen } = useResumeEnhancer();
  const { isAuthenticated } = useUnifiedAuth();
  const [isGenerating, setIsGenerating] = useState(false);
  const [isEditing, setIsEditing] = useState(true);
  const [templateType, setTemplateType] = useState<any>(() => {
    const normalized = normalizeCoverLetterMetadata(state.autoGeneratedCoverLetterMetadata);
    return normalized.templateType || 'modern';
  });

  // AI Configuration State
  const [aiMode, setAiMode] = useState<'manual' | 'assist' | 'full'>('assist');
  const [aiTone, setAiTone] = useState('Professional');
  const [aiLength, setAiLength] = useState(50); // 0-100 scale
  const [aiCreativity, setAiCreativity] = useState(30); // 0-100 scale
  const [aiPersonalization, setAiPersonalization] = useState(70); // 0-100 scale
  
  const [skipExperience, setSkipExperience] = useState(false);
  const [skipProjects, setSkipProjects] = useState(false);

  // UI State
  const [zoom, setZoom] = useState(100);
  const [pageFormat, setPageFormat] = useState<'a4' | 'letter'>('a4');
  const [activeLeftSidebar, setActiveLeftSidebar] = useState<string | null>(null);
  const [grammarIssues, setGrammarIssues] = useState<any[]>([]);
  const [matchScore, setMatchScore] = useState(82);
  const [showMoriChat, setShowMoriChat] = useState(false);
  const [showGuidePanel, setShowGuidePanel] = useState(false);
  const [showTemplateSelector, setShowTemplateSelector] = useState(false);
  const previewRef = useRef<HTMLDivElement>(null);
  const containerRef = useRef<HTMLDivElement>(null);

  // Design State
  const [design, setDesign] = useState<CoverLetterDesignProps>(() => {
    const normalized = normalizeCoverLetterMetadata(state.autoGeneratedCoverLetterMetadata);
    return normalized.design || {
      fontSize: 15,
      lineHeight: 1.6,
      pageMargin: 6,
      accentColor: '#80FF00',
      fontFamily: 'font-sans'
    };
  });

  // Sync templateType and design changes to global state
  useEffect(() => {
    dispatch({
      type: 'SET_AUTO_COVER_LETTER',
      payload: {
        draft: state.autoGeneratedCoverLetter || '',
        metadata: { templateType, design }
      }
    });
  }, [templateType, design, dispatch, state.autoGeneratedCoverLetter]);

  const hasJD = !!(state.jobData?.description || state.jobData?.jobDescription);
  const [isOffline, setIsOffline] = useState(false);

  // Auto-select template based on CV template ID
  useEffect(() => {
    if (state.autoGeneratedCoverLetterMetadata?.templateType) return;
    const templateId = state.selectedTemplate?.id || (state.selectedTemplate as any)?._id;
    if (templateId) {
      const lowerId = templateId.toLowerCase();
      if (lowerId.includes('classic') || lowerId.includes('traditional') || lowerId.includes('harvard')) {
        setTemplateType('classic');
        setDesign(prev => ({ ...prev, fontFamily: 'font-serif' }));
      } else if (lowerId.includes('minimal') || lowerId.includes('simple')) {
        setTemplateType('minimal');
        setDesign(prev => ({ ...prev, fontFamily: 'font-sans' }));
      } else {
        setTemplateType('modern');
        setDesign(prev => ({ ...prev, fontFamily: 'font-sans' }));
      }
    }
  }, [state.selectedTemplate, state.autoGeneratedCoverLetterMetadata?.templateType]);

  useEffect(() => {
    if (state.autoGeneratedCoverLetter) {
      const issues = checkSyntaxAndGrammar({ basics: { summary: state.autoGeneratedCoverLetter } });
      setGrammarIssues(issues);
    } else {
      setGrammarIssues([]);
    }
  }, [state.autoGeneratedCoverLetter]);

  useEffect(() => {
    if (typeof navigator !== 'undefined') {
      setIsOffline(!navigator.onLine);
    }
    const handleOnline = () => setIsOffline(false);
    const handleOffline = () => setIsOffline(true);
    window.addEventListener('online', handleOnline);
    window.addEventListener('offline', handleOffline);
    return () => {
      window.removeEventListener('online', handleOnline);
      window.removeEventListener('offline', handleOffline);
    };
  }, []);

  // Handle Ctrl/Cmd + Wheel to zoom the canvas area specifically, not the window
  useEffect(() => {
    const container = containerRef.current;
    if (!container) return;

    let accumulatedDelta = 0;

    const handleWheel = (e: WheelEvent) => {
      if (e.ctrlKey || e.metaKey) {
        e.preventDefault();
        
        accumulatedDelta += -e.deltaY;

        if (Math.abs(accumulatedDelta) >= 50) {
          const direction = Math.sign(accumulatedDelta);
          setZoom((prev: number) => {
            const next = prev + (direction * 10);
            const snapped = Math.round(next / 10) * 10;
            return Math.min(200, Math.max(50, snapped));
          });
          accumulatedDelta = 0;
        }
      }
    };

    container.addEventListener('wheel', handleWheel, { passive: false });
    return () => {
      container.removeEventListener('wheel', handleWheel);
    };
  }, []);

  const handleGenerate = async () => {
    if (!state.cvData || !state.jobData) {
      toast.error('CV and Job Description are required for AI generation.');
      return;
    }

    setIsGenerating(true);
    const loadingToast = toast.loading('AI is crafting your tailored letter...');
    
    try {
      const response = await fetch('/api/ai/cover-letter-generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          cvData: state.cvData,
          jobData: state.jobData,
          recipientName: state.jobData?.contactPerson || 'Hiring Manager',
          companyName: state.jobData?.company || 'the company',
          tone: aiTone,
          length: aiLength,
          creativity: aiCreativity,
          personalization: aiPersonalization,
          skipExperience,
          skipProjects,
          mode: aiMode
        })
      });
      
      const data = await response.json();
      
      if (response.ok && data.success) {
        const generatedText = data.body || data.content;
        dispatch({ 
          type: 'SET_AUTO_COVER_LETTER', 
          payload: { 
            draft: generatedText,
            metadata: data.structuredContent?.metadata
          } 
        });
        toast.success('Success! Your letter has been tailored.', { id: loadingToast });
        
        // Update match quality if returned
        if (data.structuredContent?.metadata?.match_quality) {
            setMatchScore(data.structuredContent.metadata.match_quality);
        }
      } else {
        throw new Error(data.error || 'Failed to generate');
      }
    } catch (error) {
      console.error('Failed to generate cover letter:', error);
      toast.error('AI Assistant is currently unavailable. Please try again.', { id: loadingToast });
    } finally {
      setIsGenerating(false);
    }
  };

  const handleBodyChange = (newContent: string) => {
    dispatch({ 
      type: 'SET_AUTO_COVER_LETTER', 
      payload: { draft: newContent } 
    });
  };

  const stripHtml = (html: string) => {
    if (!html) return '';
    return html.replace(/<[^>]*>/g, '').trim();
  };

  const today = new Date().toLocaleDateString('en-GB', { day: '2-digit', month: '2-digit', year: 'numeric' });
  const name = stripHtml(state.cvData?.basics?.name || 'Your Name');
  const email = stripHtml(state.cvData?.basics?.email || 'email@example.com');
  const phone = stripHtml(state.cvData?.basics?.phone || '');
  const location = stripHtml(state.cvData?.basics?.location?.city ? [state.cvData.basics.location.city, state.cvData.basics.location.countryCode].filter(Boolean).join(', ') : '');
  const recipientName = stripHtml(state.jobData?.contactPerson || 'Hiring Manager');
  const companyName = stripHtml(state.jobData?.company || 'Company Name');

  return (
    <div className="flex flex-col h-[calc(100vh-64px)] min-h-0 relative overflow-hidden bg-gray-50 dark:bg-[var(--bg-primary)]">
      <div className="flex-1 h-full flex overflow-hidden relative px-3 pb-3 pt-3 gap-3">
        
        {/* Canvas Wrapper */}
        <div className="flex-1 min-h-0 relative flex flex-col rounded-xl overflow-hidden shadow-sm shadow-black/10 dark:shadow-black/30 border border-gray-200 dark:border-white/5 text-gray-900">
          <div ref={containerRef} className="flex-1 min-h-0 overflow-y-auto bg-gray-100/50 dark:bg-[#141810] p-4 lg:p-8 flex justify-center custom-scrollbar">
            <div className="transition-transform duration-300 transform origin-top pb-20" style={{ transform: `scale(${zoom / 100})` }}>
              <CoverLetterLayoutEngine 
                templateType={templateType}
                onTemplateTypeChange={setTemplateType}
                pageFormat={pageFormat}
                headerProps={{
                  name,
                  email,
                  phone,
                  location,
                  date: today,
                  recipientName,
                  companyName
                }}
                bodyContent={state.autoGeneratedCoverLetter || ''}
                isEditing={isEditing}
                onBodyChange={handleBodyChange}
                design={design}
                zoom={zoom}
                showMoriChat={showMoriChat}
                onToggleMoriChat={() => setShowMoriChat(!showMoriChat)}
                onChangeHeaderStyle={() => setShowTemplateSelector(true)}
              />
            </div>
          </div>

          {/* Floating Zoom & Page Controls */}
          <div className="absolute bottom-6 right-6 z-[40] hidden md:flex items-center gap-2 pointer-events-none">
            <div className="px-3 h-9 rounded-xl border shadow-xl backdrop-blur-md flex items-center gap-3 text-[10px] font-bold uppercase tracking-wider bg-white/90 dark:bg-[#111]/90 text-gray-900 dark:text-gray-100 border-gray-200 dark:border-[#2a2a2a] opacity-90 hover:opacity-100 transition-opacity pointer-events-auto">
              <button 
                onClick={() => setPageFormat(pageFormat === 'a4' ? 'letter' : 'a4')}
                className="flex items-center gap-1.5 px-1.5 py-0.5 rounded-md transition-all hover:bg-emerald-500/10 text-emerald-600 dark:text-[#7EE787]"
              >
                <Layout size={10} />
                {pageFormat === 'a4' ? 'A4' : 'Letter'}
              </button>
            </div>

            <div className="px-2 h-9 rounded-xl border shadow-xl backdrop-blur-md flex items-center gap-2 bg-white/90 dark:bg-[#111]/90 text-gray-900 dark:text-gray-100 border-gray-200 dark:border-[#2a2a2a] opacity-90 hover:opacity-100 transition-opacity pointer-events-auto">
              <div className="flex items-center gap-0.5">
                <button 
                  onClick={() => setZoom(Math.max(50, zoom - 10))}
                  className={`p-1.5 rounded-lg hover:bg-emerald-500/20 transition-all ${zoom <= 50 ? 'opacity-30 cursor-not-allowed' : 'text-gray-500 dark:text-gray-400'}`}
                >
                  <Search size={14} className="rotate-90" />
                </button>
                <input 
                  type="range" min="50" max="200" step="5" value={zoom} 
                  onChange={(e) => setZoom(parseInt(e.target.value))}
                  className="w-20 accent-emerald-500 h-1 bg-gray-200 dark:bg-gray-700 rounded-lg appearance-none cursor-pointer"
                />
                <button 
                  onClick={() => setZoom(Math.min(200, zoom + 10))}
                  className={`p-1.5 rounded-lg hover:bg-emerald-500/20 transition-all ${zoom >= 200 ? 'opacity-30 cursor-not-allowed' : 'text-gray-500 dark:text-gray-400'}`}
                >
                  <Search size={14} />
                </button>
              </div>
              
              <button 
                onClick={() => setZoom(100)}
                className={`min-w-[42px] px-1.5 py-1 text-[9px] font-black rounded-md transition-all border ${zoom === 100 ? 'bg-emerald-500/20 border-emerald-500/50 text-emerald-600' : 'bg-transparent border-gray-500/20 hover:border-[#80FF00]/50 text-gray-500 dark:text-gray-400'}`}
              >
                {zoom}%
              </button>
            </div>
          </div>
        </div>

        {/* MIDDLE COLUMN - LETTER GUIDE (radial progress, metrics, context) */}
        <div 
          className={`
            fixed inset-y-0 right-0 z-50 w-full bg-white dark:bg-[#0a0a0a] flex flex-col h-full gap-3 min-h-0 shadow-2xl transition-all duration-300
            lg:static lg:w-[400px] lg:shadow-none lg:flex lg:z-10 lg:p-0 lg:overflow-hidden lg:bg-transparent
            ${showGuidePanel || showTemplateSelector ? 'translate-x-0' : 'translate-x-full lg:translate-x-0'}
          `}
          style={{ order: (showMoriChat || showGuidePanel || showTemplateSelector) ? 1 : 2 }}
        >
          {showTemplateSelector ? (
            <div className="flex flex-col h-full bg-white dark:bg-[#141810] border border-gray-200 dark:border-white/5 rounded-2xl shadow-sm overflow-hidden">
              {/* Panel Header */}
              <div className="px-4 py-3 border-b border-gray-200 dark:border-white/10 flex items-center justify-between bg-white dark:bg-transparent shrink-0">
                <div className="flex items-center gap-2 text-xs font-bold text-slate-700 dark:text-slate-300">
                  <LayoutTemplate className="w-4 h-4 text-emerald-500" />
                  <span>Header Styles</span>
                </div>
                <button 
                  onClick={() => setShowTemplateSelector(false)}
                  className="p-1 rounded-full hover:bg-gray-150 dark:hover:bg-white/5 text-slate-400 hover:text-slate-600 transition-colors"
                >
                  <X className="w-4 h-4" />
                </button>
              </div>

              {/* Panel Thumbnails List */}
              <div className="flex-1 overflow-y-auto custom-scrollbar p-4 space-y-4 bg-gray-50 dark:bg-[#0a0a0a]">
                {TEMPLATES.map((t) => {
                  const isSelected = templateType === t.id;
                  const PreviewHeaderComponent = (() => {
                    switch (t.id) {
                      case 'classic': return ClassicHeader;
                      case 'minimal': return MinimalHeader;
                      case 'typographic': return TypographicHeader;
                      case 'column-split': return ColumnSplitHeader;
                      case 'accent-banner': return AccentBannerHeader;
                      case 'creative-edge': return CreativeEdgeHeader;
                      case 'executive-slate': return ExecutiveSlateHeader;
                      case 'modern':
                      default: return ModernHeader;
                    }
                  })();

                  return (
                    <div 
                      key={t.id} 
                      onClick={() => {
                        setTemplateType(t.id);
                        if (t.id === 'classic') {
                          setDesign(prev => ({ ...prev, fontFamily: 'font-serif' }));
                        } else {
                          setDesign(prev => ({ ...prev, fontFamily: 'font-sans' }));
                        }
                      }} 
                      className={`group relative rounded-xl border-2 cursor-pointer transition-all overflow-hidden flex flex-col hover:shadow-lg bg-white dark:bg-[#111] ${
                        isSelected 
                          ? 'border-emerald-500 ring-2 ring-emerald-500/20' 
                          : 'border-gray-200 dark:border-white/5 hover:border-gray-400'
                      }`}
                    >
                      <div className="p-3 flex flex-col gap-1 z-10 border-b border-gray-100 dark:border-[#222]">
                        <div className="flex justify-between items-start">
                          <div>
                            <div className="font-bold text-xs text-gray-900 dark:text-gray-100 uppercase tracking-tight">{t.name}</div>
                            <div className="text-[9px] font-semibold uppercase tracking-wider text-gray-400 mt-0.5">{t.desc}</div>
                          </div>
                          {isSelected && (
                            <span className="bg-emerald-500/20 text-emerald-500 text-[8px] px-1.5 py-0.5 rounded font-bold tracking-widest uppercase">ACTIVE</span>
                          )}
                        </div>
                      </div>
                      
                      <div className="relative w-full aspect-[16/9] overflow-hidden bg-[#f9f9f9]">
                        <div 
                          className="absolute top-0 left-0 origin-top-left pointer-events-none p-4 opacity-95 group-hover:opacity-100 transition-opacity cv-document text-gray-900" 
                          style={{ 
                            width: '250%', 
                            transform: 'scale(0.4)',
                            '--cv-accent': design.accentColor || '#80FF00',
                            '--cv-font': design.fontFamily === 'font-serif' ? 'Merriweather' : 'Inter'
                          } as React.CSSProperties}
                        >
                          <PreviewHeaderComponent {...{
                            name,
                            email,
                            phone,
                            location,
                            date: today,
                            recipientName,
                            companyName
                          }} />
                        </div>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          ) : (
            <LetterGuidePanel 
              matchScore={matchScore}
              templateType={templateType}
              setTemplateType={setTemplateType}
              design={design}
              setDesign={setDesign}
              isEditing={isEditing}
              setIsEditing={setIsEditing}
              onComplete={onComplete}
              onUpdateTarget={() => setJobSidebarOpen(true)}
              showMoriChat={showMoriChat}
              onToggleMoriChat={() => {
                setShowMoriChat(!showMoriChat);
                setShowGuidePanel(false);
              }}
            />
          )}
        </div>

        {/* RIGHT COLUMN - MORI AI ASSISTANT CHAT */}
        <AnimatePresence>
          {showMoriChat && (
            <motion.div 
              initial={{ opacity: 0, x: 20, width: 0 }}
              animate={{ opacity: 1, x: 0, width: 360 }}
              exit={{ opacity: 0, x: 20, width: 0 }}
              transition={{ type: 'spring', damping: 25, stiffness: 200 }}
              className="fixed inset-y-0 right-0 z-50 w-full lg:static lg:w-[360px] flex flex-col shrink-0 h-full relative min-h-0 overflow-hidden shadow-2xl lg:shadow-none bg-white dark:bg-[var(--bg-secondary)]"
              style={{ order: 3 }}
            >
              <MoriCoverLetterChat 
                onBodyChange={handleBodyChange} 
                onClose={() => setShowMoriChat(false)}
              />
            </motion.div>
          )}
        </AnimatePresence>
      </div>

      {/* Mobile unified bottom navigation pill */}
      <div className="fixed bottom-6 left-1/2 -translate-x-1/2 z-[60] md:hidden flex items-center gap-2 bg-white/90 dark:bg-[#141810]/90 backdrop-blur-md border border-lime-200 dark:border-lime-900/30 rounded-2xl p-1.5 shadow-2xl no-print">
        {/* Zoom & Page Format controls (hidden if a panel is open) */}
        {!showMoriChat && !showGuidePanel && (
          <>
            <button 
              onClick={() => setPageFormat(pageFormat === 'a4' ? 'letter' : 'a4')}
              className="p-2 rounded-xl text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white hover:bg-gray-150 dark:hover:bg-white/5 transition-all border-none bg-transparent"
              title="Toggle Page Format"
            >
              <Layout size={16} />
            </button>
            <div className="w-px h-5 bg-gray-200 dark:bg-white/10 mx-1" />
          </>
        )}

        {/* Panel Buttons */}
        <div className="flex items-center gap-1">
          {/* Guide Panel */}
          <button
            onClick={() => {
              setShowGuidePanel(!showGuidePanel);
              setShowMoriChat(false);
            }}
            className={`p-2 rounded-xl transition-all border-none bg-transparent ${
              showGuidePanel
                ? 'bg-emerald-500/20 text-emerald-600 dark:text-emerald-400'
                : 'text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white'
            }`}
            title="Letter Guide"
          >
            <Target size={16} />
          </button>

          {/* Mori Chat */}
          <button
            onClick={() => {
              setShowMoriChat(!showMoriChat);
              setShowGuidePanel(false);
            }}
            className={`p-2 rounded-xl transition-all border-none bg-transparent ${
              showMoriChat
                ? 'bg-emerald-500/20 text-emerald-600 dark:text-emerald-400'
                : 'text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white'
            }`}
            title="Mori Chat"
          >
            <Sparkles size={16} />
          </button>
        </div>
      </div>

      <EditorOnboarding step={4} />
    </div>
  );
}
