/**
 * DOCX Service
 * 
 * Provides high-fidelity DOCX/DOC conversion from CV data
 */

import { UnifiedCVDataStructure } from '@/types/unified-cv-schema';
import { ITemplate } from '@/types/template';
import { templateRendererService } from './templateRendererService';
import { stripHtmlTags } from '@/lib/utils/textFormatting';
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, WidthType, Table, TableRow, TableCell, BorderStyle } from 'docx';
import { BaseService } from './baseService';
import { configService } from './configService';

/**
 * Convert hex color string to DOCX-compatible hex (without # prefix, uppercase)
 */
function hexToDocxColor(hex: string | undefined): string | undefined {
  if (!hex) return undefined;
  const cleaned = hex.replace('#', '').toUpperCase();
  // Validate hex color (3 or 6 chars)
  if (/^[0-9A-Fa-f]{3}$/.test(cleaned)) {
    // Expand shorthand hex (e.g., F00 -> FF0000)
    return cleaned.split('').map(c => c + c).join('');
  }
  if (/^[0-9A-Fa-f]{6}$/.test(cleaned)) {
    return cleaned;
  }
  return undefined;
}

/**
 * Extract a clean font family name from CSS font-family string
 * Returns the first font in the list, cleaned of quotes
 */
function extractFontFamily(fontFamily: string | undefined): string {
  if (!fontFamily) return 'Calibri';
  // Take the first font from the list
  const firstFont = fontFamily.split(',')[0].trim().replace(/['"]/g, '');
  // Map common web fonts to their Word equivalents
  const fontMap: Record<string, string> = {
    'Inter': 'Calibri',
    'Lato': 'Calibri',
    'Montserrat': 'Arial',
    'Playfair Display': 'Georgia',
    'Helvetica Neue': 'Helvetica',
    'Helvetica': 'Helvetica',
    'Roboto': 'Calibri',
    'Open Sans': 'Calibri',
    'Georgia': 'Georgia',
    'Times New Roman': 'Times New Roman',
    'Arial': 'Arial',
    'Calibri': 'Calibri',
  };
  return fontMap[firstFont] || firstFont || 'Calibri';
}

export interface DOCXGenerationOptions {
  paperSize?: 'A4' | 'Letter';
  orientation?: 'portrait' | 'landscape';
  format?: 'docx' | 'doc';
}

export class DOCXService extends BaseService {
  private static instance: DOCXService;

  private constructor() {
    super('DOCXService');
  }

  static getInstance(): DOCXService {
    if (!DOCXService.instance) {
      DOCXService.instance = new DOCXService();
    }
    return DOCXService.instance;
  }

  /**
   * Generate DOCX from CV data and template
   */
  static async generateDOCX(
    cvData: UnifiedCVDataStructure,
    template: ITemplate,
    options: DOCXGenerationOptions = {}
  ): Promise<Blob> {
    const instance = DOCXService.getInstance();
    return instance.generateDOCXInternal(cvData, template, options);
  }

  private async generateDOCXInternal(
    cvData: UnifiedCVDataStructure,
    template: ITemplate,
    options: DOCXGenerationOptions = {}
  ): Promise<Blob> {
    return this.timeOperation('generateDOCX', async () => {
      return this.withRetry(
        async () => {
          try {
            // Extract template styling
            const fontFamily = extractFontFamily(template?.globalStyles?.fontFamily);
            const primaryColorHex = hexToDocxColor(template?.globalStyles?.primaryColor);
            const secondaryColorHex = hexToDocxColor(template?.globalStyles?.secondaryColor);

            // Build heading color config
            const headingColor = primaryColorHex ? { color: primaryColorHex } : {};

            // For high-fidelity conversion, we'll use structured docx generation
            // This preserves formatting better than HTML conversion
            // ATS-friendly: Use standard fonts and proper document structure
            const doc = new Document({
              creator: 'CVCircle',
              title: cvData.basics?.name ? `${cvData.basics.name} - CV` : 'CV/Resume',
              description: 'Professional CV/Resume generated by CVCircle',
              styles: {
                default: {
                  document: {
                    run: {
                      font: fontFamily,
                      size: 22 // 11pt
                    },
                    paragraph: {
                      spacing: {
                        line: 276, // 1.15 line spacing
                        lineRule: 'auto'
                      }
                    }
                  },
                  heading1: {
                    run: {
                      font: fontFamily,
                      size: 32, // 16pt
                      bold: true,
                      ...headingColor
                    },
                    paragraph: {
                      spacing: { after: 200 }
                    }
                  },
                  heading2: {
                    run: {
                      font: fontFamily,
                      size: 26, // 13pt
                      bold: true,
                      ...headingColor
                    },
                    paragraph: {
                      spacing: { before: 300, after: 200 }
                    }
                  },
                  heading3: {
                    run: {
                      font: fontFamily,
                      size: 24, // 12pt
                      bold: true,
                      ...(secondaryColorHex ? { color: secondaryColorHex } : headingColor)
                    },
                    paragraph: {
                      spacing: { after: 100 }
                    }
                  }
                }
              },
              sections: [{
                properties: {
                  page: {
                    size: {
                      // DOCX uses twips (1/20th of a point = 1/1440th of an inch)
                      // A4: 210mm x 297mm, Letter: 216mm x 279mm (8.5in x 11in)
                      width: options.paperSize === 'Letter' ? 12240 : 11906, // in twips
                      height: options.paperSize === 'Letter' ? 15840 : 16838
                    },
                    margin: {
                      // Match PDF margins: 12mm top/bottom, 15mm left/right
                      // Convert to twips: 12mm ≈ 680 twips, 15mm ≈ 850 twips
                      top: 680,
                      right: 850,
                      bottom: 680,
                      left: 850
                    }
                  }
                },
                children: this.buildDocumentContent(cvData, template, fontFamily, primaryColorHex, secondaryColorHex)
              }]
            });

            const buffer = await Packer.toBuffer(doc);
            return new Blob([new Uint8Array(buffer)], {
              type: options.format === 'doc' ? 'application/msword' : 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
            });
          } catch (error) {
            throw this.handleError(error, {
              templateId: template?.id || template?._id
            });
          }
        },
        configService.getRetryConfig(),
        { templateId: template?.id || template?._id }
      );
    });
  }

  /**
   * Build document content from CV data
   */
  private buildDocumentContent(
    cvData: UnifiedCVDataStructure,
    template: ITemplate,
    fontFamily: string = 'Calibri',
    primaryColorHex?: string,
    secondaryColorHex?: string
  ): (Paragraph | Table)[] {
    const content: (Paragraph | Table)[] = [];
    const headingColor = primaryColorHex ? { color: primaryColorHex } : {};
    const bodyColor = secondaryColorHex ? { color: secondaryColorHex } : {};

    // Header - Name
    if (cvData.basics?.name) {
      content.push(
        new Paragraph({
          text: cvData.basics.name,
          heading: HeadingLevel.HEADING_1,
          alignment: AlignmentType.CENTER,
          spacing: { after: 100 }
        })
      );
    }

    // Title/Label
    if (cvData.basics?.label) {
      content.push(
        new Paragraph({
          children: [
            new TextRun({
              text: cvData.basics.label,
              font: fontFamily,
              size: 22,
              ...(secondaryColorHex ? { color: secondaryColorHex } : {})
            })
          ],
          alignment: AlignmentType.CENTER,
          spacing: { after: 200 }
        })
      );
    }

    // Contact Information
    const contactInfo: string[] = [];
    if (cvData.basics?.email) contactInfo.push(cvData.basics.email);
    if (cvData.basics?.phone) contactInfo.push(cvData.basics.phone);
    if (cvData.basics?.location?.city) {
      const locationParts = [
        cvData.basics.location.city,
        cvData.basics.location.region,
        cvData.basics.location.countryCode
      ].filter(Boolean);
      contactInfo.push(locationParts.join(', '));
    }
    // Add website/profiles
    if (cvData.basics?.url) contactInfo.push(cvData.basics.url);
    if (cvData.basics?.profiles && cvData.basics.profiles.length > 0) {
      cvData.basics.profiles.forEach(profile => {
        if (profile.url) contactInfo.push(profile.url);
      });
    }

    if (contactInfo.length > 0) {
      content.push(
        new Paragraph({
          children: contactInfo.map((info, index) =>
            new TextRun({
              text: info + (index < contactInfo.length - 1 ? ' | ' : ''),
              size: 20, // 10pt
              font: fontFamily,
              ...(secondaryColorHex ? { color: secondaryColorHex } : {})
            })
          ),
          alignment: AlignmentType.CENTER,
          spacing: { after: 300 }
        })
      );
    }

    // Horizontal rule after header
    content.push(
      new Paragraph({
        spacing: { after: 200 },
        border: {
          bottom: {
            style: BorderStyle.SINGLE,
            size: 6,
            color: primaryColorHex || '1E40AF',
            space: 1
          }
        }
      })
    );

    // Summary
    if (cvData.basics?.summary) {
      content.push(
        new Paragraph({
          text: 'Professional Summary',
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 100, after: 150 }
        }),
        new Paragraph({
          children: [
            new TextRun({
              text: stripHtmlTags(cvData.basics.summary),
              font: fontFamily,
              size: 22
            })
          ],
          spacing: { after: 300 }
        })
      );
    }

    // Work Experience
    if (cvData.work && cvData.work.length > 0) {
      content.push(
        new Paragraph({
          text: 'Work Experience',
          heading: HeadingLevel.HEADING_2
        })
      );

      cvData.work.forEach((work) => {
        content.push(
          new Paragraph({
            text: work.position || '',
            heading: HeadingLevel.HEADING_3,
            spacing: { after: 50 }
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: work.name || '',
                bold: true,
                font: fontFamily,
                size: 22,
                ...(secondaryColorHex ? { color: secondaryColorHex } : {})
              }),
              new TextRun({
                text: ` | ${work.startDate || ''} - ${work.endDate || 'Present'}`,
                font: fontFamily,
                size: 22,
                ...(secondaryColorHex ? { color: secondaryColorHex } : {})
              })
            ],
            spacing: { after: 100 }
          })
        );

        if (work.summary) {
          content.push(
            new Paragraph({
              children: [
                new TextRun({
                  text: stripHtmlTags(work.summary),
                  font: fontFamily,
                  size: 22
                })
              ],
              spacing: { after: 100 }
            })
          );
        }

        if (work.highlights && work.highlights.length > 0) {
          work.highlights.forEach((highlight) => {
            content.push(
              new Paragraph({
                children: [
                  new TextRun({
                    text: `• ${highlight}`,
                    font: fontFamily,
                    size: 22
                  })
                ],
                indent: { left: 720 }, // 0.5 inch
                spacing: { after: 50 }
              })
            );
          });
        }

        content.push(new Paragraph({ text: '', spacing: { after: 150 } }));
      });
    }

    // Education
    if (cvData.education && cvData.education.length > 0) {
      content.push(
        new Paragraph({
          text: 'Education',
          heading: HeadingLevel.HEADING_2
        })
      );

      cvData.education.forEach((edu) => {
        content.push(
          new Paragraph({
            text: `${edu.studyType || ''}${edu.area ? ` in ${edu.area}` : ''}`,
            heading: HeadingLevel.HEADING_3,
            spacing: { after: 50 }
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: edu.institution || '',
                bold: true,
                font: fontFamily,
                size: 22,
                ...(secondaryColorHex ? { color: secondaryColorHex } : {})
              }),
              new TextRun({
                text: ` | ${edu.startDate || ''} - ${edu.endDate || 'Present'}`,
                font: fontFamily,
                size: 22,
                ...(secondaryColorHex ? { color: secondaryColorHex } : {})
              })
            ],
            spacing: { after: 100 }
          })
        );

        if (edu.score) {
          content.push(
            new Paragraph({
              children: [
                new TextRun({
                  text: `GPA: ${edu.score}`,
                  font: fontFamily,
                  size: 22
                })
              ],
              spacing: { after: 150 }
            })
          );
        }

        if (edu.courses && edu.courses.length > 0) {
          content.push(
            new Paragraph({
              children: [
                new TextRun({
                  text: `Relevant Coursework: ${edu.courses.join(', ')}`,
                  font: fontFamily,
                  size: 20,
                  italics: true
                })
              ],
              spacing: { after: 150 }
            })
          );
        }
      });
    }

    // Skills
    if (cvData.skills && cvData.skills.length > 0) {
      content.push(
        new Paragraph({
          text: 'Skills',
          heading: HeadingLevel.HEADING_2
        })
      );

      // Group skills by category
      const skillsByCategory = cvData.skills.reduce((acc, skill) => {
        const category = skill.category || 'Other';
        if (!acc[category]) {
          acc[category] = [];
        }
        acc[category].push(...(skill.skills || []));
        return acc;
      }, {} as Record<string, string[]>);

      Object.entries(skillsByCategory).forEach(([category, skills]) => {
        content.push(
          new Paragraph({
            children: [
              new TextRun({
                text: `${category}: `,
                bold: true,
                font: fontFamily,
                size: 22,
                ...(primaryColorHex ? { color: primaryColorHex } : {})
              }),
              new TextRun({
                text: skills.join(', '),
                font: fontFamily,
                size: 22
              })
            ],
            spacing: { after: 80 }
          })
        );
      });
    }

    // Projects
    if (cvData.projects && cvData.projects.length > 0) {
      content.push(
        new Paragraph({
          text: 'Projects',
          heading: HeadingLevel.HEADING_2
        })
      );

      cvData.projects.forEach((project) => {
        content.push(
          new Paragraph({
            text: project.name || '',
            heading: HeadingLevel.HEADING_3,
            spacing: { after: 50 }
          })
        );

        if (project.description) {
          content.push(
            new Paragraph({
              children: [
                new TextRun({
                  text: stripHtmlTags(project.description),
                  font: fontFamily,
                  size: 22
                })
              ],
              spacing: { after: 100 }
            })
          );
        }

        if (project.highlights && project.highlights.length > 0) {
          project.highlights.forEach((highlight) => {
            content.push(
              new Paragraph({
                children: [
                  new TextRun({
                    text: `• ${highlight}`,
                    font: fontFamily,
                    size: 22
                  })
                ],
                indent: { left: 720 },
                spacing: { after: 50 }
              })
            );
          });
        }

        if (project.url) {
          content.push(
            new Paragraph({
              children: [
                new TextRun({
                  text: project.url,
                  font: fontFamily,
                  size: 20,
                  ...(primaryColorHex ? { color: primaryColorHex } : {})
                })
              ],
              spacing: { after: 150 }
            })
          );
        }
      });
    }

    // Certificates
    if (cvData.certificates && cvData.certificates.length > 0) {
      content.push(
        new Paragraph({
          text: 'Certificates',
          heading: HeadingLevel.HEADING_2
        })
      );

      cvData.certificates.forEach((cert) => {
        content.push(
          new Paragraph({
            children: [
              new TextRun({
                text: cert.name || '',
                bold: true,
                font: fontFamily,
                size: 22,
                ...(primaryColorHex ? { color: primaryColorHex } : {})
              }),
              ...(cert.issuer ? [
                new TextRun({
                  text: ` | ${cert.issuer}`,
                  font: fontFamily,
                  size: 22,
                  ...(secondaryColorHex ? { color: secondaryColorHex } : {})
                })
              ] : []),
              ...(cert.date ? [
                new TextRun({
                  text: ` | ${cert.date}`,
                  font: fontFamily,
                  size: 22,
                  ...(secondaryColorHex ? { color: secondaryColorHex } : {})
                })
              ] : [])
            ],
            spacing: { after: 80 }
          })
        );
      });
    }

    // Languages
    if (cvData.languages && cvData.languages.length > 0) {
      content.push(
        new Paragraph({
          text: 'Languages',
          heading: HeadingLevel.HEADING_2
        })
      );

      content.push(
        new Paragraph({
          children: cvData.languages.map((lang, index) =>
            new TextRun({
              text: `${lang.language || ''}: ${lang.fluency || ''}${index < cvData.languages!.length - 1 ? '  •  ' : ''}`,
              font: fontFamily,
              size: 22
            })
          ),
          spacing: { after: 200 }
        })
      );
    }

    // Volunteer
    if (cvData.volunteer && cvData.volunteer.length > 0) {
      content.push(
        new Paragraph({
          text: 'Volunteer Experience',
          heading: HeadingLevel.HEADING_2
        })
      );

      cvData.volunteer.forEach((vol) => {
        content.push(
          new Paragraph({
            text: vol.position || '',
            heading: HeadingLevel.HEADING_3,
            spacing: { after: 50 }
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: vol.organization || '',
                bold: true,
                font: fontFamily,
                size: 22,
                ...(secondaryColorHex ? { color: secondaryColorHex } : {})
              }),
              new TextRun({
                text: ` | ${vol.startDate || ''} - ${vol.endDate || 'Present'}`,
                font: fontFamily,
                size: 22,
                ...(secondaryColorHex ? { color: secondaryColorHex } : {})
              })
            ],
            spacing: { after: 100 }
          })
        );

        if (vol.summary) {
          content.push(
            new Paragraph({
              children: [
                new TextRun({
                  text: stripHtmlTags(vol.summary),
                  font: fontFamily,
                  size: 22
                })
              ],
              spacing: { after: 150 }
            })
          );
        }
      });
    }

    // Awards
    if (cvData.awards && cvData.awards.length > 0) {
      content.push(
        new Paragraph({
          text: 'Awards',
          heading: HeadingLevel.HEADING_2
        })
      );

      cvData.awards.forEach((award) => {
        content.push(
          new Paragraph({
            children: [
              new TextRun({
                text: award.title || '',
                bold: true,
                font: fontFamily,
                size: 22,
                ...(primaryColorHex ? { color: primaryColorHex } : {})
              }),
              ...(award.awarder ? [
                new TextRun({
                  text: ` | ${award.awarder}`,
                  font: fontFamily,
                  size: 22,
                  ...(secondaryColorHex ? { color: secondaryColorHex } : {})
                })
              ] : []),
              ...(award.date ? [
                new TextRun({
                  text: ` | ${award.date}`,
                  font: fontFamily,
                  size: 22,
                  ...(secondaryColorHex ? { color: secondaryColorHex } : {})
                })
              ] : [])
            ],
            spacing: { after: 80 }
          })
        );

        if (award.summary) {
          content.push(
            new Paragraph({
              children: [
                new TextRun({
                  text: stripHtmlTags(award.summary),
                  font: fontFamily,
                  size: 22
                })
              ],
              spacing: { after: 150 }
            })
          );
        }
      });
    }

    // Publications
    if (cvData.publications && cvData.publications.length > 0) {
      content.push(
        new Paragraph({
          text: 'Publications',
          heading: HeadingLevel.HEADING_2
        })
      );

      cvData.publications.forEach((pub) => {
        content.push(
          new Paragraph({
            text: pub.name || '',
            heading: HeadingLevel.HEADING_3,
            spacing: { after: 50 }
          })
        );

        if (pub.publisher || pub.releaseDate) {
          content.push(
            new Paragraph({
              children: [
                new TextRun({
                  text: [pub.publisher, pub.releaseDate].filter(Boolean).join(' | '),
                  font: fontFamily,
                  size: 22,
                  ...(secondaryColorHex ? { color: secondaryColorHex } : {})
                })
              ],
              spacing: { after: 100 }
            })
          );
        }

        if (pub.summary) {
          content.push(
            new Paragraph({
              children: [
                new TextRun({
                  text: stripHtmlTags(pub.summary),
                  font: fontFamily,
                  size: 22
                })
              ],
              spacing: { after: 150 }
            })
          );
        }
      });
    }

    // Interests
    if (cvData.interests && cvData.interests.length > 0) {
      content.push(
        new Paragraph({
          text: 'Interests',
          heading: HeadingLevel.HEADING_2
        }),
        new Paragraph({
          children: [
            new TextRun({
              text: cvData.interests.map((interest) =>
                typeof interest === 'string' ? interest : interest.name
              ).join('  •  '),
              font: fontFamily,
              size: 22
            })
          ],
          spacing: { after: 200 }
        })
      );
    }

    // References
    if (cvData.references && cvData.references.length > 0) {
      content.push(
        new Paragraph({
          text: 'References',
          heading: HeadingLevel.HEADING_2
        })
      );

      cvData.references.forEach((ref: any) => {
        content.push(
          new Paragraph({
            children: [
              new TextRun({
                text: ref.name || '',
                bold: true,
                font: fontFamily,
                size: 22
              })
            ],
            spacing: { after: 50 }
          })
        );

        const refDetails = [ref.position, ref.company].filter(Boolean).join(' at ');
        if (refDetails) {
          content.push(
            new Paragraph({
              children: [
                new TextRun({
                  text: refDetails,
                  font: fontFamily,
                  size: 22,
                  ...(secondaryColorHex ? { color: secondaryColorHex } : {})
                })
              ],
              spacing: { after: 50 }
            })
          );
        }

        const refContact = [ref.email, ref.phone].filter(Boolean).join(' | ');
        if (refContact) {
          content.push(
            new Paragraph({
              children: [
                new TextRun({
                  text: refContact,
                  font: fontFamily,
                  size: 20,
                  ...(secondaryColorHex ? { color: secondaryColorHex } : {})
                })
              ],
              spacing: { after: 150 }
            })
          );
        }
      });
    }

    return content;
  }
}

export const docxService = DOCXService;

