import { UnifiedCVDataStructure } from '@/types/unified-cv-schema';

export interface GuestDraftData {
  cvData: UnifiedCVDataStructure;
  currentStep: number;
  completedSteps: number[];
  activeSection?: string;
  availableSections?: string[];
  targetRole?: string;
  seniorityLevel?: string;
  templateId?: string;
  template?: any;
  cvTitle?: string;
  aiAnalysis?: any;
  jobData?: any;
  autoGeneratedCoverLetter?: string;
}

export interface SaveDraftResponse {
  success: boolean;
  draftId?: string;
  sessionId?: string;
  error?: string;
}

export interface LoadDraftResponse {
  success: boolean;
  data?: GuestDraftData;
  error?: string;
}

export interface TransferDraftResponse {
  success: boolean;
  cvId?: string;
  step?: number;
  error?: string;
}

class GuestCVService {
  private readonly DRAFT_SESSION_COOKIE = 'cv-draft-session-id';
  private readonly DRAFT_STORAGE_KEY = 'guest-cv-draft';
  private autoSaveInterval: NodeJS.Timeout | null = null;

  /**
   * Generate or retrieve session ID for guest user
   */
  getSessionId(): string {
    if (typeof window === 'undefined') return '';

    // Try to get from cookie
    const cookies = document.cookie.split(';');
    const sessionCookie = cookies.find(c => c.trim().startsWith(`${this.DRAFT_SESSION_COOKIE}=`));
    if (sessionCookie) {
      return sessionCookie.split('=')[1]?.trim() || '';
    }

    // Generate new session ID
    const newSessionId = `guest-${Date.now()}-${Math.random().toString(36).substring(2, 15)}`;
    this.setSessionCookie(newSessionId);
    return newSessionId;
  }

  /**
   * Set session ID cookie
   */
  private setSessionCookie(sessionId: string): void {
    if (typeof document === 'undefined') return;
    
    const expires = new Date();
    expires.setTime(expires.getTime() + 7 * 24 * 60 * 60 * 1000); // 7 days
    
    document.cookie = `${this.DRAFT_SESSION_COOKIE}=${sessionId}; expires=${expires.toUTCString()}; path=/; SameSite=Lax`;
  }

  /**
   * Save draft to server (TemporaryCVDraft)
   */
  async saveGuestDraft(data: GuestDraftData, sessionId?: string): Promise<SaveDraftResponse> {
    try {
      const effectiveSessionId = sessionId || this.getSessionId();
      if (!effectiveSessionId) {
        return { success: false, error: 'No session ID available' };
      }

      // If data doesn't have aiAnalysis, check if we have one in local storage and merge it!
      if (!data.aiAnalysis) {
        const existing = this.loadFromLocalStorage();
        if (existing && existing.aiAnalysis) {
          data.aiAnalysis = existing.aiAnalysis;
        }
      }

      // Also save to localStorage as backup
      this.saveToLocalStorage(data);

      const response = await fetch('/api/cv-draft/save', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          cvData: data.cvData,
          currentStep: data.currentStep,
          completedSteps: data.completedSteps,
          activeSection: data.activeSection,
          availableSections: data.availableSections,
          targetRole: data.targetRole,
          seniorityLevel: data.seniorityLevel,
          templateId: data.templateId,
          template: data.template,
          cvTitle: data.cvTitle,
          aiAnalysis: data.aiAnalysis,
          jobData: data.jobData,
          autoGeneratedCoverLetter: data.autoGeneratedCoverLetter,
          isForMasterCV: true,
          sessionId: effectiveSessionId
        })
      });

      const result = await response.json();
      
      if (!response.ok) {
        console.error('Failed to save guest draft:', result.error);
        return { success: false, error: result.error || 'Failed to save draft' };
      }

      // Update session ID if returned
      if (result.sessionId && result.sessionId !== effectiveSessionId) {
        this.setSessionCookie(result.sessionId);
      }

      return {
        success: true,
        draftId: result.draftId,
        sessionId: result.sessionId || effectiveSessionId
      };
    } catch (error: any) {
      console.error('Error saving guest draft:', error);
      // Fallback to localStorage only
      this.saveToLocalStorage(data);
      return { success: false, error: error.message || 'Network error saving draft' };
    }
  }

  /**
   * Load draft from server
   */
  async loadGuestDraft(sessionId?: string): Promise<LoadDraftResponse> {
    try {
      const effectiveSessionId = sessionId || this.getSessionId();
      if (!effectiveSessionId) {
        // Try to load from localStorage as fallback
        const localData = this.loadFromLocalStorage();
        if (localData) {
          return { success: true, data: localData };
        }
        return { success: false, error: 'No session ID available' };
      }

      const response = await fetch(`/api/cv-draft/load?sessionId=${effectiveSessionId}`);
      const result = await response.json();

      if (!response.ok || !result.success) {
        // Try localStorage fallback
        const localData = this.loadFromLocalStorage();
        if (localData) {
          return { success: true, data: localData };
        }
        return { success: false, error: result.error || 'Failed to load draft' };
      }

      if (result.data) {
        // Also save to localStorage as backup
        this.saveToLocalStorage(result.data);
        return { success: true, data: result.data };
      }

      // Try localStorage fallback
      const localData = this.loadFromLocalStorage();
      if (localData) {
        return { success: true, data: localData };
      }

      return { success: false, error: 'No draft data found' };
    } catch (error: any) {
      console.error('Error loading guest draft:', error);
      // Try localStorage fallback
      const localData = this.loadFromLocalStorage();
      if (localData) {
        return { success: true, data: localData };
      }
      return { success: false, error: error.message || 'Network error loading draft' };
    }
  }

  /**
   * Transfer draft to authenticated user account
   */
  async transferDraftToUser(sessionId?: string, userId?: string): Promise<TransferDraftResponse> {
    try {
      const effectiveSessionId = sessionId || this.getSessionId();
      if (!effectiveSessionId) {
        return { success: false, error: 'No session ID available' };
      }

      const response = await fetch('/api/cv-draft/transfer', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          sessionId: effectiveSessionId,
          userId: userId
        })
      });

      const result = await response.json();

      if (!response.ok || !result.success) {
        return { success: false, error: result.error || 'Failed to transfer draft' };
      }

      // Clear localStorage after successful transfer
      this.clearLocalStorage();

      return {
        success: true,
        cvId: result.cvId,
        step: result.step
      };
    } catch (error: any) {
      console.error('Error transferring draft:', error);
      return { success: false, error: error.message || 'Network error transferring draft' };
    }
  }

  /**
   * Save to localStorage as backup
   */
  private saveToLocalStorage(data: GuestDraftData): void {
    if (typeof window === 'undefined') return;
    
    try {
      const storageData = {
        ...data,
        savedAt: Date.now()
      };
      localStorage.setItem(this.DRAFT_STORAGE_KEY, JSON.stringify(storageData));
    } catch (error) {
      console.warn('Failed to save to localStorage:', error);
      // Storage quota exceeded - try to clear old data
      try {
        localStorage.removeItem(this.DRAFT_STORAGE_KEY);
        localStorage.setItem(this.DRAFT_STORAGE_KEY, JSON.stringify(data));
      } catch (e) {
        console.error('Failed to save to localStorage after cleanup:', e);
      }
    }
  }

  /**
   * Load from localStorage
   */
  private loadFromLocalStorage(): GuestDraftData | null {
    if (typeof window === 'undefined') return null;
    
    try {
      const stored = localStorage.getItem(this.DRAFT_STORAGE_KEY);
      if (!stored) return null;

      const data = JSON.parse(stored);
      // Check if data is not too old (7 days)
      const savedAt = data.savedAt || 0;
      const sevenDaysAgo = Date.now() - 7 * 24 * 60 * 60 * 1000;
      
      if (savedAt < sevenDaysAgo) {
        this.clearLocalStorage();
        return null;
      }

      // Remove savedAt before returning
      delete data.savedAt;
      return data;
    } catch (error) {
      console.warn('Failed to load from localStorage:', error);
      return null;
    }
  }

  /**
   * Clear localStorage
   */
  clearLocalStorage(): void {
    if (typeof window === 'undefined') return;
    try {
      localStorage.removeItem(this.DRAFT_STORAGE_KEY);
    } catch (error) {
      console.warn('Failed to clear localStorage:', error);
    }
  }

  /**
   * Start auto-save interval
   */
  startAutoSave(
    getData: () => GuestDraftData,
    intervalMs: number = 30000
  ): void {
    this.stopAutoSave();
    
    this.autoSaveInterval = setInterval(async () => {
      const data = getData();
      if (data.cvData) {
        await this.saveGuestDraft(data);
      }
    }, intervalMs);
  }

  /**
   * Stop auto-save interval
   */
  stopAutoSave(): void {
    if (this.autoSaveInterval) {
      clearInterval(this.autoSaveInterval);
      this.autoSaveInterval = null;
    }
  }

  /**
   * Check if draft exists
   */
  async hasDraft(sessionId?: string): Promise<boolean> {
    const result = await this.loadGuestDraft(sessionId);
    return result.success && !!result.data;
  }
}

export default new GuestCVService();

